In [1]:
import pandas as pd
bos = pd.read_csv('boston_edited.csv')
boston = bos[['city', 'state', 'closed_date', 'calendar_year', 'amount_awarded']]

In [2]:
boston

      city state closed_date  calendar_year  amount_awarded
0   Boston    MA  2010-01-14           2010         2000.00
1   Boston    MA         NaN           2010        85000.00
2   Boston    MA  2010-05-05           2010         6000.00
3   Boston    MA  2010-05-27           2010        12000.00
4   Boston    MA  2010-08-14           2010        25000.00
5   Boston    MA  2010-10-10           2010        15000.00
6   Boston    MA  2010-12-28           2010        16950.00
7   Boston    MA  2011-03-01           2011        11000.00
8   Boston    MA  2011-10-28           2011        34500.00
9   Boston    MA  2012-02-16           2012      1400000.00
10  Boston    MA  2012-03-05           2012       170000.00
11  Boston    MA  2012-04-18           2012        60000.00
12  Boston    MA         NaN           2012        33000.00
13  Boston    MA  2012-07-11           2012         6000.00
14  Boston    MA  2012-07-19           2012       150000.00
15  Boston    MA  2012-09-12           2012        30000.00
16  Boston    MA  2012-10-09           2012        25000.00
17  Boston    MA  2012-10-12           2012       115000.00
18  Boston    MA  2013-01-25           2013        20000.00
19  Boston    MA  2013-05-03           2013        50000.00
20  Boston    MA  2013-05-03           2013       239139.50
21  Boston    MA  2013-06-26           2013        85000.00
22  Boston    MA         NaN           2013        10000.00
23  Boston    MA  2013-09-20           2013      3000000.00
24  Boston    MA  2013-10-22           2013        75000.00
25  Boston    MA  2013-10-25           2013        12000.00
26  Boston    MA  2014-03-14           2014      5000000.00
27  Boston    MA  2014-05-15           2014        50000.00
28  Boston    MA  2014-06-02           2014       100000.00
29  Boston    MA  2014-12-12           2014        25000.00
30  Boston    MA         NaN           2015        75000.00
31  Boston    MA         NaN           2015        18500.00
32  Boston    MA  2015-06-09           2015        29000.00
33  Boston    MA  2015-06-10           2015        52500.00
34  Boston    MA  2015-10-15           2015         5000.00
35  Boston    MA  2015-11-18           2015       179892.36
36  Boston    MA  2016-11-07           2016        45000.00
37  Boston    MA  2016-03-16           2016        18000.00
38  Boston    MA  2016-06-06           2016       120000.00
39  Boston    MA  2016-07-15           2016        12500.00
40  Boston    MA  2016-09-12           2016        12500.00
41  Boston    MA  2017-05-05           2017         5000.00
42  Boston    MA  2017-07-05           2017         5000.00
43  Boston    MA  2017-07-06           2017        60000.00
44  Boston    MA  2018-02-16           2018        15000.00
45  Boston    MA  2018-08-14           2018         5000.00
46  Boston    MA  2018-09-25           2018        10000.00
47  Boston    MA  2018-10-30           2018       250000.00
48  Boston    MA  2018-12-20           2018        10000.00
49  Boston    MA  2019-01-30           2019       100000.00
50  Boston    MA  2019-05-19           2019        15000.00

In [3]:
cam = pd.read_csv('cambridge_edited.csv')
cambridge = cam[['city', 'state', 'closed_date', 'incident_date_full', 'calendar_year', 'amount_awarded']]
cambridge

,city,state,closed_date,incident_date_full,calendar_year,amount_awarded
0,Cambridge,MA,NaN,"6/28/2010; June 2011, October 2012, October 2014",NaN,2500
1,Cambridge,MA,NaN,2006-12-18,NaN,50000
2,Cambridge,MA,NaN,2013-11-14,NaN,54000
3,Cambridge,MA,NaN,2012-06-15,NaN,7500

In [4]:
charl = pd.read_csv('charleston_edited.csv')
charleston = charl[['city', 'state', 'closed_date', 'calendar_year', 'amount_awarded']]
charleston

          city state closed_date  calendar_year  amount_awarded
0   Charleston    SC  2016-06-03           2016               0
1   Charleston    SC  2014-04-07           2014               0
2   Charleston    SC  2012-04-04           2012           12500
3   Charleston    SC  2016-04-15           2016           25000
4   Charleston    SC  2019-08-08           2019           65000
5   Charleston    SC  2013-04-15           2013            8000
6   Charleston    SC  2019-12-15           2019            4000
7   Charleston    SC  2012-06-18           2012           23000
8   Charleston    SC  2017-01-06           2017          150000
9   Charleston    SC  2013-02-28           2013           50000
10  Charleston    SC  2016-06-03           2016           80000
11  Charleston    SC  2015-03-17           2015            8000
12  Charleston    SC  2017-06-13           2017           10000
13  Charleston    SC  2015-02-18           2015            5000
14  Charleston    SC  2019-06-24           2019           10000
15  Charleston    SC  2016-06-29           2016            3000
16  Charleston    SC  2015-01-29           2015           10000
17  Charleston    SC  2014-11-12           2014          600000
18  Charleston    SC  2013-10-11           2013            6000
19  Charleston    SC  2013-12-05           2013               0
20  Charleston    SC  2017-02-16           2017           57500
21  Charleston    SC  2018-07-18           2018           80000
22  Charleston    SC  2015-12-23           2015               0
23  Charleston    SC  2010-07-28           2010            5500
24  Charleston    SC  2019-01-24           2019           85000
25  Charleston    SC  2011-01-24           2011            4000
26  Charleston    SC  2014-12-03           2014            1000
27  Charleston    SC  2018-03-08           2018          100000
28  Charleston    SC  2014-05-05           2014               0
29  Charleston    SC  2017-05-05           2017               0
30  Charleston    SC  2015-07-02           2015               0
31  Charleston    SC  2018-08-06           2018               0
32  Charleston    SC  2011-11-07           2011               0
33  Charleston    SC  2010-04-19           2010               0
34  Charleston    SC  2010-05-28           2010               0
35  Charleston    SC  2011-06-23           2011               0
36  Charleston    SC  2011-10-03           2011               0
37  Charleston    SC  2013-08-01           2013               0
38  Charleston    SC  2012-04-24           2012               0
39  Charleston    SC  2011-09-07           2011               0
40  Charleston    SC  2012-07-30           2012               0
41  Charleston    SC  2014-08-11           2014               0
42  Charleston    SC  2018-07-23           2018               0
43  Charleston    SC  2018-03-08           2018           25000
44  Charleston    SC  2014-06-04           2014            5000
45  Charleston    SC  2019-04-15           2019           22500
46  Charleston    SC  2011-10-03           2011               0
47  Charleston    SC  2013-03-11           2013           20000
48  Charleston    SC  2014-03-19           2014               0
49  Charleston    SC  2017-07-27           2017               0
50  Charleston    SC  2012-09-04           2012               0
51  Charleston    SC  2015-10-30           2015               0
52  Charleston    SC  2012-07-16           2012               0
53  Charleston    SC  2017-03-29           2017           40000
54  Charleston    SC  2017-03-29           2017            2500
55  Charleston    SC  2017-03-29           2017            2500
56  Charleston    SC  2016-12-30           2016             250
57  Charleston    SC  2015-12-21           2015               0
58  Charleston    SC  2018-05-04           2018               0

In [5]:
cin = pd.read_csv('cincinnati_edited.csv')
cincinnati = cin[['city', 'state', 'closed_date', 'calendar_year', 'amount_awarded']]
cincinnati

          city state closed_date  calendar_year  amount_awarded
0   Cincinnati    OH  2015-10-29           2015       130000.00
1   Cincinnati    OH  2014-03-03           2014         9000.00
2   Cincinnati    OH  2015-04-06           2015          500.00
3   Cincinnati    OH  2014-01-24           2014        50000.00
4   Cincinnati    OH  2014-12-17           2014       505000.00
5   Cincinnati    OH  2012-09-27           2012        90000.00
6   Cincinnati    OH  2011-01-01           2011         5000.00
7   Cincinnati    OH  2014-04-08           2014        37000.00
8   Cincinnati    OH  2012-06-12           2012        60000.00
9   Cincinnati    OH  2015-08-20           2015        12500.00
10  Cincinnati    OH  2017-07-13           2017         5500.00
11  Cincinnati    OH  2011-12-06           2011        22750.00
12  Cincinnati    OH  2015-06-18           2015         9000.00
13  Cincinnati    OH  2019-03-14           2019        11000.00
14  Cincinnati    OH  2015-12-09           2015        15000.00
15  Cincinnati    OH  2020-04-15           2020        24000.00
16  Cincinnati    OH  2018-07-24           2018       100000.00
17  Cincinnati    OH  2017-07-13           2017        15500.00
18  Cincinnati    OH  2017-05-08           2017        95000.00
19  Cincinnati    OH  2018-03-06           2018        87770.31
20  Cincinnati    OH  2017-07-13           2017         2350.00
21  Cincinnati    OH  2019-12-31           2019         4037.83
22  Cincinnati    OH  2019-04-30           2019        15000.00
23  Cincinnati    OH  2019-01-11           2019       220000.00
24  Cincinnati    OH  2010-11-05           2010         5000.00
25  Cincinnati    OH  2012-09-19           2012        17500.00
26  Cincinnati    OH  2011-12-19           2011         5000.00
27  Cincinnati    OH  2019-07-17           2019       151000.00
28  Cincinnati    OH  2015-01-14           2015        25000.00
29  Cincinnati    OH  2020-07-06           2020       100000.00
30  Cincinnati    OH  2014-10-01           2014         6000.00
31  Cincinnati    OH  2018-10-22           2018        25000.00
32  Cincinnati    OH  2013-10-25           2013        40000.00
33  Cincinnati    OH  2012-01-03           2012        30000.00
34  Cincinnati    OH  2014-09-17           2014         4250.00
35  Cincinnati    OH  2014-12-15           2014         3000.00
36  Cincinnati    OH  2019-04-08           2019         9793.00
37  Cincinnati    OH  2019-01-07           2019        90000.00
38  Cincinnati    OH  2015-09-17           2015       187500.00
39  Cincinnati    OH  2013-01-15           2013        25000.00
40  Cincinnati    OH  2017-07-13           2017         2250.00
41  Cincinnati    OH  2012-06-06           2012        29500.00
42  Cincinnati    OH  2017-08-07           2017        13500.00
43  Cincinnati    OH  2014-12-04           2014        15000.00
44  Cincinnati    OH  2016-11-07           2016         8000.00
45  Cincinnati    OH  2014-10-01           2014         7500.00
46  Cincinnati    OH  2012-12-12           2012         3000.00
47  Cincinnati    OH  2017-07-13           2017        12500.00
48  Cincinnati    OH  2019-09-27           2019        27847.49
49  Cincinnati    OH  2017-07-13           2017        62838.35
50  Cincinnati    OH  2010-06-24           2010         5900.00
51  Cincinnati    OH  2012-06-27           2012         5000.00
52  Cincinnati    OH  2016-03-15           2016        17500.00
53  Cincinnati    OH  2017-07-13           2017        12500.00

In [6]:
col = pd.read_csv('columbia_edited.csv')
columbia = col[['city', 'state', 'closed_date', 'calendar_year', 'amount_awarded']]
columbia

        city state closed_date  calendar_year  amount_awarded
0   Columbia    SC  2017-09-05         2017.0           25000
1   Columbia    SC  2013-07-19         2013.0           50000
2   Columbia    SC  2017-07-31         2017.0            5000
3   Columbia    SC  2013-12-18         2013.0           13500
4   Columbia    SC  2019-03-28         2019.0            2500
5   Columbia    SC         NaN         2018.0           18000
6   Columbia    SC  2015-10-13         2015.0            3000
7   Columbia    SC  2010-11-16         2010.0              10
8   Columbia    SC  2012-10-05         2012.0           15000
9   Columbia    SC  2018-07-30         2018.0           10000
10  Columbia    SC  2015-01-30         2015.0           25000
11  Columbia    SC  2018-12-06         2018.0            8625
12  Columbia    SC  2014-09-22         2014.0           15000
13  Columbia    SC         NaN            NaN          300000
14  Columbia    SC  2016-03-18         2016.0          180000
15  Columbia    SC  2017-07-03         2017.0           15000
16  Columbia    SC  2016-12-05         2016.0           60000
17  Columbia    SC  2015-09-18         2015.0           12800
18  Columbia    SC         NaN            NaN           15000
19  Columbia    SC  2017-03-03         2017.0           22000
20  Columbia    SC  2013-02-15         2013.0           43000
21  Columbia    SC  2014-10-02         2014.0           27500
22  Columbia    SC  2015-01-02         2015.0           13500
23  Columbia    SC  2013-04-17         2013.0           10000
24  Columbia    SC  2016-05-02         2016.0          185000
25  Columbia    SC  2010-09-17         2010.0            4500
26  Columbia    SC  2017-05-17         2017.0            8000
27  Columbia    SC         NaN            NaN            6500
28  Columbia    SC  2016-06-13         2016.0            9000
29  Columbia    SC  2017-01-12         2017.0          250000

In [7]:
lr = pd.read_csv('little_rock_edited.csv')
little_rock = lr[['city', 'state', 'closed_date', 'incident_date', 'calendar_year', 'amount_awarded']]
little_rock

          city state  closed_date incident_date  calendar_year  amount_awarded
0  Little Rock    AR          NaN    2008-12-20            NaN            5000
1  Little Rock    AR          NaN    2008-04-10            NaN           10000
2  Little Rock    AR          NaN    2010-08-12            NaN            2700
3  Little Rock    AR          NaN    2012-07-01            NaN            6750
4  Little Rock    AR          NaN    2011-10-29            NaN           15000
5  Little Rock    AR          NaN    2009-11-03            NaN           90000
6  Little Rock    AR          NaN    2010-12-09            NaN          810000
7  Little Rock    AR          NaN    2015-06-01            NaN            4500

In [8]:
orl = pd.read_csv('orlando_edited.csv')
orlando = orl[['city', 'state', 'closed_date', 'incident_date', 'calendar_year', 'amount_awarded']]
orlando

       city state closed_date incident_date  calendar_year  amount_awarded
0   Orlando    FL  2012-11-14    2010-03-29         2012.0         6000.00
1   Orlando    FL  2015-03-20    2010-06-15         2015.0         4000.00
2   Orlando    FL  2014-03-03    2010-08-10         2014.0        90000.00
3   Orlando    FL         NaN    2010-09-18            NaN       880000.00
4   Orlando    FL  2013-03-04    2010-11-11         2013.0         3000.00
5   Orlando    FL         NaN    2010-11-21            NaN       750000.00
6   Orlando    FL         NaN    2011-02-25            NaN       140000.00
7   Orlando    FL         NaN    2011-04-21            NaN        24999.99
8   Orlando    FL         NaN    2011-12-03            NaN        17500.00
9   Orlando    FL         NaN    2011-12-30            NaN        15000.00
10  Orlando    FL         NaN    2011-12-30            NaN         5000.00
11  Orlando    FL         NaN    2012-08-01            NaN       100000.00
12  Orlando    FL         NaN    2012-09-12            NaN        10000.00
13  Orlando    FL         NaN    2012-12-12            NaN         5000.00
14  Orlando    FL         NaN    2013-01-01            NaN        30000.00
15  Orlando    FL         NaN    2013-01-15            NaN       125000.00
16  Orlando    FL         NaN    2013-01-16            NaN       760000.00
17  Orlando    FL         NaN    2013-01-22            NaN        15000.00
18  Orlando    FL  2015-05-21    2013-04-30         2015.0        75000.00
19  Orlando    FL  2016-06-08    2013-03-24         2016.0        40000.00
20  Orlando    FL  2014-07-07    2013-03-23         2014.0         5000.00
21  Orlando    FL  2016-05-19    2013-02-27         2016.0         5000.00
22  Orlando    FL  2017-01-23    2013-08-02         2017.0         3000.00
23  Orlando    FL  2016-04-12    2013-09-26         2016.0         5000.00
24  Orlando    FL  2017-06-16    2013-10-04         2017.0        50000.00
25  Orlando    FL  2015-05-29    2013-12-07         2015.0        40878.60
26  Orlando    FL  2018-08-20    2014-07-05         2018.0        95000.00
27  Orlando    FL  2016-10-11    2014-08-07         2016.0         5000.00
28  Orlando    FL  2017-06-16    2014-08-08         2017.0        24999.99
29  Orlando    FL  2019-02-15    2014-08-10         2019.0         2500.00
30  Orlando    FL  2019-02-15    2014-08-10         2019.0         2500.00
31  Orlando    FL  2017-09-26    2014-08-12         2017.0        80000.00
32  Orlando    FL  2016-07-08    2014-11-16         2016.0         7500.00
33  Orlando    FL  2020-06-25    2015-06-04         2020.0        95000.00
34  Orlando    FL  2016-10-20    2014-07-05         2016.0         5000.00
35  Orlando    FL  2020-06-10    2016-01-06         2020.0        50000.00
36  Orlando    FL  2019-01-07    2017-03-04         2019.0        15000.00
37  Orlando    FL  2019-08-23    2018-01-04         2019.0        25000.00

In [9]:
all_cities = pd.concat([boston, cambridge, charleston, cincinnati, columbia, little_rock, orlando])

In [10]:
pd.set_option('display.max_rows', None)
all_cities

,city,state,closed_date,calendar_year,amount_awarded,incident_date_full,incident_date
0,Boston,MA,2010-01-14,2010.0,2000.00,NaN,NaN
1,Boston,MA,NaN,2010.0,85000.00,NaN,NaN
2,Boston,MA,2010-05-05,2010.0,6000.00,NaN,NaN
3,Boston,MA,2010-05-27,2010.0,12000.00,NaN,NaN
4,Boston,MA,2010-08-14,2010.0,25000.00,NaN,NaN
5,Boston,MA,2010-10-10,2010.0,15000.00,NaN,NaN
6,Boston,MA,2010-12-28,2010.0,16950.00,NaN,NaN
7,Boston,MA,2011-03-01,2011.0,11000.00,NaN,NaN
8,Boston,MA,2011-10-28,2011.0,34500.00,NaN,NaN
9,Boston,MA,2012-02-16,2012.0,1400000.00,NaN,NaN
10,Boston,MA,2012-03-05,2012.0,170000.00,NaN,NaN
11,Boston,MA,2012-04-18,2012.0,60000.00,NaN,NaN
12,Boston,MA,NaN,2012.0,33000.00,NaN,NaN
13,Boston,MA,2012-07-11,2012.0,6000.00,NaN,NaN
14,Boston,MA,2012-07-19,2012.0,150000.00,NaN,NaN
15,Boston,MA,2012-09-12,2012.0,30000.00,NaN,NaN
16,Boston,MA,2012-10-09,2012.0,25000.00,NaN,NaN
17,Boston,MA,2012-10-12,2012.0,115000.00,NaN,NaN
18,Boston,MA,2013-01-25,2013.0,20000.00,NaN,NaN
19,Boston,MA,2013-05-03,2013.0,50000.00,NaN,NaN
20,Boston,MA,2013-05-03,2013.0,239139.50,NaN,NaN
21,Boston,MA,2013-06-26,2013.0,85000.00,NaN,NaN
22,Boston,MA,NaN,2013.0,10000.00,NaN,NaN
23,Boston,MA,2013-09-20,2013.0,3000000.00,NaN,NaN
24,Boston,MA,2013-10-22,2013.0,75000.00,NaN,NaN
25,Boston,MA,2013-10-25,2013.0,12000.00,NaN,NaN
26,Boston,MA,2014-03-14,2014.0,5000000.00,NaN,NaN
27,Boston,MA,2014-05-15,2014.0,50000.00,NaN,NaN
28,Boston,MA,2014-06-02,2014.0,100000.00,NaN,NaN
29,Boston,MA,2014-12-12,2014.0,25000.00,NaN,NaN
30,Boston,MA,NaN,2015.0,75000.00,NaN,NaN
31,Boston,MA,NaN,2015.0,18500.00,NaN,NaN
32,Boston,MA,2015-06-09,2015.0,29000.00,NaN,NaN
33,Boston,MA,2015-06-10,2015.0,52500.00,NaN,NaN
34,Boston,MA,2015-10-15,2015.0,5000.00,NaN,NaN
35,Boston,MA,2015-11-18,2015.0,179892.36,NaN,NaN
36,Boston,MA,2016-11-07,2016.0,45000.00,NaN,NaN
37,Boston,MA,2016-03-16,2016.0,18000.00,NaN,NaN
38,Boston,MA,2016-06-06,2016.0,120000.00,NaN,NaN
39,Boston,MA,2016-07-15,2016.0,12500.00,NaN,NaN
40,Boston,MA,2016-09-12,2016.0,12500.00,NaN,NaN
41,Boston,MA,2017-05-05,2017.0,5000.00,NaN,NaN
42,Boston,MA,2017-07-05,2017.0,5000.00,NaN,NaN
43,Boston,MA,2017-07-06,2017.0,60000.00,NaN,NaN
44,Boston,MA,2018-02-16,2018.0,15000.00,NaN,NaN
45,Boston,MA,2018-08-14,2018.0,5000.00,NaN,NaN
46,Boston,MA,2018-09-25,2018.0,10000.00,NaN,NaN
47,Boston,MA,2018-10-30,2018.0,250000.00,NaN,NaN
48,Boston,MA,2018-12-20,2018.0,10000.00,NaN,NaN
49,Boston,MA,2019-01-30,2019.0,100000.00,NaN,NaN
50,Boston,MA,2019-05-19,2019.0,15000.00,NaN,NaN
0,Cambridge,MA,NaN,NaN,2500.00,"6/28/2010; June 2011, October 2012, October 2014",NaN
1,Cambridge,MA,NaN,NaN,50000.00,2006-12-18,NaN
2,Cambridge,MA,NaN,NaN,54000.00,2013-11-14,NaN
3,Cambridge,MA,NaN,NaN,7500.00,2012-06-15,NaN
0,Charleston,SC,2016-06-03,2016.0,0.00,NaN,NaN
1,Charleston,SC,2014-04-07,2014.0,0.00,NaN,NaN
2,Charleston,SC,2012-04-04,2012.0,12500.00,NaN,NaN
3,Charleston,SC,2016-04-15,2016.0,25000.00,NaN,NaN
4,Charleston,SC,2019-08-08,2019.0,65000.00,NaN,NaN
5,Charleston,SC,2013-04-15,2013.0,8000.00,NaN,NaN
6,Charleston,SC,2019-12-15,2019.0,4000.00,NaN,NaN
7,Charleston,SC,2012-06-18,2012.0,23000.00,NaN,NaN
8,Charleston,SC,2017-01-06,2017.0,150000.00,NaN,NaN
9,Charleston,SC,2013-02-28,2013.0,50000.00,NaN,NaN
10,Charleston,SC,2016-06-03,2016.0,80000.00,NaN,NaN
11,Charleston,SC,2015-03-17,2015.0,8000.00,NaN,NaN
12,Charleston,SC,2017-06-13,2017.0,10000.00,NaN,NaN
13,Charleston,SC,2015-02-18,2015.0,5000.00,NaN,NaN
14,Charleston,SC,2019-06-24,2019.0,10000.00,NaN,NaN
15,Charleston,SC,2016-06-29,2016.0,3000.00,NaN,NaN
16,Charleston,SC,2015-01-29,2015.0,10000.00,NaN,NaN
17,Charleston,SC,2014-11-12,2014.0,600000.00,NaN,NaN
18,Charleston,SC,2013-10-11,2013.0,6000.00,NaN,NaN
19,Charleston,SC,2013-12-05,2013.0,0.00,NaN,NaN
20,Charleston,SC,2017-02-16,2017.0,57500.00,NaN,NaN
21,Charleston,SC,2018-07-18,2018.0,80000.00,NaN,NaN
22,Charleston,SC,2015-12-23,2015.0,0.00,NaN,NaN
23,Charleston,SC,2010-07-28,2010.0,5500.00,NaN,NaN
24,Charleston,SC,2019-01-24,2019.0,85000.00,NaN,NaN
25,Charleston,SC,2011-01-24,2011.0,4000.00,NaN,NaN
26,Charleston,SC,2014-12-03,2014.0,1000.00,NaN,NaN
27,Charleston,SC,2018-03-08,2018.0,100000.00,NaN,NaN
28,Charleston,SC,2014-05-05,2014.0,0.00,NaN,NaN
29,Charleston,SC,2017-05-05,2017.0,0.00,NaN,NaN
30,Charleston,SC,2015-07-02,2015.0,0.00,NaN,NaN
31,Charleston,SC,2018-08-06,2018.0,0.00,NaN,NaN
32,Charleston,SC,2011-11-07,2011.0,0.00,NaN,NaN
33,Charleston,SC,2010-04-19,2010.0,0.00,NaN,NaN
34,Charleston,SC,2010-05-28,2010.0,0.00,NaN,NaN
35,Charleston,SC,2011-06-23,2011.0,0.00,NaN,NaN
36,Charleston,SC,2011-10-03,2011.0,0.00,NaN,NaN
37,Charleston,SC,2013-08-01,2013.0,0.00,NaN,NaN
38,Charleston,SC,2012-04-24,2012.0,0.00,NaN,NaN
39,Charleston,SC,2011-09-07,2011.0,0.00,NaN,NaN
40,Charleston,SC,2012-07-30,2012.0,0.00,NaN,NaN
41,Charleston,SC,2014-08-11,2014.0,0.00,NaN,NaN
42,Charleston,SC,2018-07-23,2018.0,0.00,NaN,NaN
43,Charleston,SC,2018-03-08,2018.0,25000.00,NaN,NaN
44,Charleston,SC,2014-06-04,2014.0,5000.00,NaN,NaN
45,Charleston,SC,2019-04-15,2019.0,22500.00,NaN,NaN
46,Charleston,SC,2011-10-03,2011.0,0.00,NaN,NaN
47,Charleston,SC,2013-03-11,2013.0,20000.00,NaN,NaN
48,Charleston,SC,2014-03-19,2014.0,0.00,NaN,NaN
49,Charleston,SC,2017-07-27,2017.0,0.00,NaN,NaN
50,Charleston,SC,2012-09-04,2012.0,0.00,NaN,NaN
51,Charleston,SC,2015-10-30,2015.0,0.00,NaN,NaN
52,Charleston,SC,2012-07-16,2012.0,0.00,NaN,NaN
53,Charleston,SC,2017-03-29,2017.0,40000.00,NaN,NaN
54,Charleston,SC,2017-03-29,2017.0,2500.00,NaN,NaN
55,Charleston,SC,2017-03-29,2017.0,2500.00,NaN,NaN
56,Charleston,SC,2016-12-30,2016.0,250.00,NaN,NaN
57,Charleston,SC,2015-12-21,2015.0,0.00,NaN,NaN
58,Charleston,SC,2018-05-04,2018.0,0.00,NaN,NaN
0,Cincinnati,OH,2015-10-29,2015.0,130000.00,NaN,NaN
1,Cincinnati,OH,2014-03-03,2014.0,9000.00,NaN,NaN
2,Cincinnati,OH,2015-04-06,2015.0,500.00,NaN,NaN
3,Cincinnati,OH,2014-01-24,2014.0,50000.00,NaN,NaN
4,Cincinnati,OH,2014-12-17,2014.0,505000.00,NaN,NaN
5,Cincinnati,OH,2012-09-27,2012.0,90000.00,NaN,NaN
6,Cincinnati,OH,2011-01-01,2011.0,5000.00,NaN,NaN
7,Cincinnati,OH,2014-04-08,2014.0,37000.00,NaN,NaN
8,Cincinnati,OH,2012-06-12,2012.0,60000.00,NaN,NaN
9,Cincinnati,OH,2015-08-20,2015.0,12500.00,NaN,NaN
10,Cincinnati,OH,2017-07-13,2017.0,5500.00,NaN,NaN
11,Cincinnati,OH,2011-12-06,2011.0,22750.00,NaN,NaN
12,Cincinnati,OH,2015-06-18,2015.0,9000.00,NaN,NaN
13,Cincinnati,OH,2019-03-14,2019.0,11000.00,NaN,NaN
14,Cincinnati,OH,2015-12-09,2015.0,15000.00,NaN,NaN
15,Cincinnati,OH,2020-04-15,2020.0,24000.00,NaN,NaN
16,Cincinnati,OH,2018-07-24,2018.0,100000.00,NaN,NaN
17,Cincinnati,OH,2017-07-13,2017.0,15500.00,NaN,NaN
18,Cincinnati,OH,2017-05-08,2017.0,95000.00,NaN,NaN
19,Cincinnati,OH,2018-03-06,2018.0,87770.31,NaN,NaN
20,Cincinnati,OH,2017-07-13,2017.0,2350.00,NaN,NaN
21,Cincinnati,OH,2019-12-31,2019.0,4037.83,NaN,NaN
22,Cincinnati,OH,2019-04-30,2019.0,15000.00,NaN,NaN
23,Cincinnati,OH,2019-01-11,2019.0,220000.00,NaN,NaN
24,Cincinnati,OH,2010-11-05,2010.0,5000.00,NaN,NaN
25,Cincinnati,OH,2012-09-19,2012.0,17500.00,NaN,NaN
26,Cincinnati,OH,2011-12-19,2011.0,5000.00,NaN,NaN
27,Cincinnati,OH,2019-07-17,2019.0,151000.00,NaN,NaN
28,Cincinnati,OH,2015-01-14,2015.0,25000.00,NaN,NaN
29,Cincinnati,OH,2020-07-06,2020.0,100000.00,NaN,NaN
30,Cincinnati,OH,2014-10-01,2014.0,6000.00,NaN,NaN
31,Cincinnati,OH,2018-10-22,2018.0,25000.00,NaN,NaN
32,Cincinnati,OH,2013-10-25,2013.0,40000.00,NaN,NaN
33,Cincinnati,OH,2012-01-03,2012.0,30000.00,NaN,NaN
34,Cincinnati,OH,2014-09-17,2014.0,4250.00,NaN,NaN
35,Cincinnati,OH,2014-12-15,2014.0,3000.00,NaN,NaN
36,Cincinnati,OH,2019-04-08,2019.0,9793.00,NaN,NaN
37,Cincinnati,OH,2019-01-07,2019.0,90000.00,NaN,NaN
38,Cincinnati,OH,2015-09-17,2015.0,187500.00,NaN,NaN
39,Cincinnati,OH,2013-01-15,2013.0,25000.00,NaN,NaN
40,Cincinnati,OH,2017-07-13,2017.0,2250.00,NaN,NaN
41,Cincinnati,OH,2012-06-06,2012.0,29500.00,NaN,NaN
42,Cincinnati,OH,2017-08-07,2017.0,13500.00,NaN,NaN
43,Cincinnati,OH,2014-12-04,2014.0,15000.00,NaN,NaN
44,Cincinnati,OH,2016-11-07,2016.0,8000.00,NaN,NaN
45,Cincinnati,OH,2014-10-01,2014.0,7500.00,NaN,NaN
46,Cincinnati,OH,2012-12-12,2012.0,3000.00,NaN,NaN
47,Cincinnati,OH,2017-07-13,2017.0,12500.00,NaN,NaN
48,Cincinnati,OH,2019-09-27,2019.0,27847.49,NaN,NaN
49,Cincinnati,OH,2017-07-13,2017.0,62838.35,NaN,NaN
50,Cincinnati,OH,2010-06-24,2010.0,5900.00,NaN,NaN
51,Cincinnati,OH,2012-06-27,2012.0,5000.00,NaN,NaN
52,Cincinnati,OH,2016-03-15,2016.0,17500.00,NaN,NaN
53,Cincinnati,OH,2017-07-13,2017.0,12500.00,NaN,NaN
0,Columbia,SC,2017-09-05,2017.0,25000.00,NaN,NaN
1,Columbia,SC,2013-07-19,2013.0,50000.00,NaN,NaN
2,Columbia,SC,2017-07-31,2017.0,5000.00,NaN,NaN
3,Columbia,SC,2013-12-18,2013.0,13500.00,NaN,NaN
4,Columbia,SC,2019-03-28,2019.0,2500.00,NaN,NaN
5,Columbia,SC,NaN,2018.0,18000.00,NaN,NaN
6,Columbia,SC,2015-10-13,2015.0,3000.00,NaN,NaN
7,Columbia,SC,2010-11-16,2010.0,10.00,NaN,NaN
8,Columbia,SC,2012-10-05,2012.0,15000.00,NaN,NaN
9,Columbia,SC,2018-07-30,2018.0,10000.00,NaN,NaN
10,Columbia,SC,2015-01-30,2015.0,25000.00,NaN,NaN
11,Columbia,SC,2018-12-06,2018.0,8625.00,NaN,NaN
12,Columbia,SC,2014-09-22,2014.0,15000.00,NaN,NaN
13,Columbia,SC,NaN,NaN,300000.00,NaN,NaN
14,Columbia,SC,2016-03-18,2016.0,180000.00,NaN,NaN
15,Columbia,SC,2017-07-03,2017.0,15000.00,NaN,NaN
16,Columbia,SC,2016-12-05,2016.0,60000.00,NaN,NaN
17,Columbia,SC,2015-09-18,2015.0,12800.00,NaN,NaN
18,Columbia,SC,NaN,NaN,15000.00,NaN,NaN
19,Columbia,SC,2017-03-03,2017.0,22000.00,NaN,NaN
20,Columbia,SC,2013-02-15,2013.0,43000.00,NaN,NaN
21,Columbia,SC,2014-10-02,2014.0,27500.00,NaN,NaN
22,Columbia,SC,2015-01-02,2015.0,13500.00,NaN,NaN
23,Columbia,SC,2013-04-17,2013.0,10000.00,NaN,NaN
24,Columbia,SC,2016-05-02,2016.0,185000.00,NaN,NaN
25,Columbia,SC,2010-09-17,2010.0,4500.00,NaN,NaN
26,Columbia,SC,2017-05-17,2017.0,8000.00,NaN,NaN
27,Columbia,SC,NaN,NaN,6500.00,NaN,NaN
28,Columbia,SC,2016-06-13,2016.0,9000.00,NaN,NaN
29,Columbia,SC,2017-01-12,2017.0,250000.00,NaN,NaN
0,Little Rock,AR,NaN,NaN,5000.00,NaN,2008-12-20
1,Little Rock,AR,NaN,NaN,10000.00,NaN,2008-04-10
2,Little Rock,AR,NaN,NaN,2700.00,NaN,2010-08-12
3,Little Rock,AR,NaN,NaN,6750.00,NaN,2012-07-01
4,Little Rock,AR,NaN,NaN,15000.00,NaN,2011-10-29
5,Little Rock,AR,NaN,NaN,90000.00,NaN,2009-11-03
6,Little Rock,AR,NaN,NaN,810000.00,NaN,2010-12-09
7,Little Rock,AR,NaN,NaN,4500.00,NaN,2015-06-01
0,Orlando,FL,2012-11-14,2012.0,6000.00,NaN,2010-03-29
1,Orlando,FL,2015-03-20,2015.0,4000.00,NaN,2010-06-15
2,Orlando,FL,2014-03-03,2014.0,90000.00,NaN,2010-08-10
3,Orlando,FL,NaN,NaN,880000.00,NaN,2010-09-18
4,Orlando,FL,2013-03-04,2013.0,3000.00,NaN,2010-11-11
5,Orlando,FL,NaN,NaN,750000.00,NaN,2010-11-21
6,Orlando,FL,NaN,NaN,140000.00,NaN,2011-02-25
7,Orlando,FL,NaN,NaN,24999.99,NaN,2011-04-21
8,Orlando,FL,NaN,NaN,17500.00,NaN,2011-12-03
9,Orlando,FL,NaN,NaN,15000.00,NaN,2011-12-30
10,Orlando,FL,NaN,NaN,5000.00,NaN,2011-12-30
11,Orlando,FL,NaN,NaN,100000.00,NaN,2012-08-01
12,Orlando,FL,NaN,NaN,10000.00,NaN,2012-09-12
13,Orlando,FL,NaN,NaN,5000.00,NaN,2012-12-12
14,Orlando,FL,NaN,NaN,30000.00,NaN,2013-01-01
15,Orlando,FL,NaN,NaN,125000.00,NaN,2013-01-15
16,Orlando,FL,NaN,NaN,760000.00,NaN,2013-01-16
17,Orlando,FL,NaN,NaN,15000.00,NaN,2013-01-22
18,Orlando,FL,2015-05-21,2015.0,75000.00,NaN,2013-04-30
19,Orlando,FL,2016-06-08,2016.0,40000.00,NaN,2013-03-24
20,Orlando,FL,2014-07-07,2014.0,5000.00,NaN,2013-03-23
21,Orlando,FL,2016-05-19,2016.0,5000.00,NaN,2013-02-27
22,Orlando,FL,2017-01-23,2017.0,3000.00,NaN,2013-08-02
23,Orlando,FL,2016-04-12,2016.0,5000.00,NaN,2013-09-26
24,Orlando,FL,2017-06-16,2017.0,50000.00,NaN,2013-10-04
25,Orlando,FL,2015-05-29,2015.0,40878.60,NaN,2013-12-07
26,Orlando,FL,2018-08-20,2018.0,95000.00,NaN,2014-07-05
27,Orlando,FL,2016-10-11,2016.0,5000.00,NaN,2014-08-07
28,Orlando,FL,2017-06-16,2017.0,24999.99,NaN,2014-08-08
29,Orlando,FL,2019-02-15,2019.0,2500.00,NaN,2014-08-10
30,Orlando,FL,2019-02-15,2019.0,2500.00,NaN,2014-08-10
31,Orlando,FL,2017-09-26,2017.0,80000.00,NaN,2014-08-12
32,Orlando,FL,2016-07-08,2016.0,7500.00,NaN,2014-11-16
33,Orlando,FL,2020-06-25,2020.0,95000.00,NaN,2015-06-04
34,Orlando,FL,2016-10-20,2016.0,5000.00,NaN,2014-07-05
35,Orlando,FL,2020-06-10,2020.0,50000.00,NaN,2016-01-06
36,Orlando,FL,2019-01-07,2019.0,15000.00,NaN,2017-03-04
37,Orlando,FL,2019-08-23,2019.0,25000.00,NaN,2018-01-04

In [11]:
all_cities.to_csv('my_cities.csv')
read = pd.read_csv('my_cities.csv')
read

,Unnamed: 0,city,state,closed_date,calendar_year,amount_awarded,incident_date_full,incident_date
0,0,Boston,MA,2010-01-14,2010.0,2000.00,NaN,NaN
1,1,Boston,MA,NaN,2010.0,85000.00,NaN,NaN
2,2,Boston,MA,2010-05-05,2010.0,6000.00,NaN,NaN
3,3,Boston,MA,2010-05-27,2010.0,12000.00,NaN,NaN
4,4,Boston,MA,2010-08-14,2010.0,25000.00,NaN,NaN
5,5,Boston,MA,2010-10-10,2010.0,15000.00,NaN,NaN
6,6,Boston,MA,2010-12-28,2010.0,16950.00,NaN,NaN
7,7,Boston,MA,2011-03-01,2011.0,11000.00,NaN,NaN
8,8,Boston,MA,2011-10-28,2011.0,34500.00,NaN,NaN
9,9,Boston,MA,2012-02-16,2012.0,1400000.00,NaN,NaN
10,10,Boston,MA,2012-03-05,2012.0,170000.00,NaN,NaN
11,11,Boston,MA,2012-04-18,2012.0,60000.00,NaN,NaN
12,12,Boston,MA,NaN,2012.0,33000.00,NaN,NaN
13,13,Boston,MA,2012-07-11,2012.0,6000.00,NaN,NaN
14,14,Boston,MA,2012-07-19,2012.0,150000.00,NaN,NaN
15,15,Boston,MA,2012-09-12,2012.0,30000.00,NaN,NaN
16,16,Boston,MA,2012-10-09,2012.0,25000.00,NaN,NaN
17,17,Boston,MA,2012-10-12,2012.0,115000.00,NaN,NaN
18,18,Boston,MA,2013-01-25,2013.0,20000.00,NaN,NaN
19,19,Boston,MA,2013-05-03,2013.0,50000.00,NaN,NaN
20,20,Boston,MA,2013-05-03,2013.0,239139.50,NaN,NaN
21,21,Boston,MA,2013-06-26,2013.0,85000.00,NaN,NaN
22,22,Boston,MA,NaN,2013.0,10000.00,NaN,NaN
23,23,Boston,MA,2013-09-20,2013.0,3000000.00,NaN,NaN
24,24,Boston,MA,2013-10-22,2013.0,75000.00,NaN,NaN
25,25,Boston,MA,2013-10-25,2013.0,12000.00,NaN,NaN
26,26,Boston,MA,2014-03-14,2014.0,5000000.00,NaN,NaN
27,27,Boston,MA,2014-05-15,2014.0,50000.00,NaN,NaN
28,28,Boston,MA,2014-06-02,2014.0,100000.00,NaN,NaN
29,29,Boston,MA,2014-12-12,2014.0,25000.00,NaN,NaN
30,30,Boston,MA,NaN,2015.0,75000.00,NaN,NaN
31,31,Boston,MA,NaN,2015.0,18500.00,NaN,NaN
32,32,Boston,MA,2015-06-09,2015.0,29000.00,NaN,NaN
33,33,Boston,MA,2015-06-10,2015.0,52500.00,NaN,NaN
34,34,Boston,MA,2015-10-15,2015.0,5000.00,NaN,NaN
35,35,Boston,MA,2015-11-18,2015.0,179892.36,NaN,NaN
36,36,Boston,MA,2016-11-07,2016.0,45000.00,NaN,NaN
37,37,Boston,MA,2016-03-16,2016.0,18000.00,NaN,NaN
38,38,Boston,MA,2016-06-06,2016.0,120000.00,NaN,NaN
39,39,Boston,MA,2016-07-15,2016.0,12500.00,NaN,NaN
40,40,Boston,MA,2016-09-12,2016.0,12500.00,NaN,NaN
41,41,Boston,MA,2017-05-05,2017.0,5000.00,NaN,NaN
42,42,Boston,MA,2017-07-05,2017.0,5000.00,NaN,NaN
43,43,Boston,MA,2017-07-06,2017.0,60000.00,NaN,NaN
44,44,Boston,MA,2018-02-16,2018.0,15000.00,NaN,NaN
45,45,Boston,MA,2018-08-14,2018.0,5000.00,NaN,NaN
46,46,Boston,MA,2018-09-25,2018.0,10000.00,NaN,NaN
47,47,Boston,MA,2018-10-30,2018.0,250000.00,NaN,NaN
48,48,Boston,MA,2018-12-20,2018.0,10000.00,NaN,NaN
49,49,Boston,MA,2019-01-30,2019.0,100000.00,NaN,NaN
50,50,Boston,MA,2019-05-19,2019.0,15000.00,NaN,NaN
51,0,Cambridge,MA,NaN,NaN,2500.00,"6/28/2010; June 2011, October 2012, October 2014",NaN
52,1,Cambridge,MA,NaN,NaN,50000.00,2006-12-18,NaN
53,2,Cambridge,MA,NaN,NaN,54000.00,2013-11-14,NaN
54,3,Cambridge,MA,NaN,NaN,7500.00,2012-06-15,NaN
55,0,Charleston,SC,2016-06-03,2016.0,0.00,NaN,NaN
56,1,Charleston,SC,2014-04-07,2014.0,0.00,NaN,NaN
57,2,Charleston,SC,2012-04-04,2012.0,12500.00,NaN,NaN
58,3,Charleston,SC,2016-04-15,2016.0,25000.00,NaN,NaN
59,4,Charleston,SC,2019-08-08,2019.0,65000.00,NaN,NaN
60,5,Charleston,SC,2013-04-15,2013.0,8000.00,NaN,NaN
61,6,Charleston,SC,2019-12-15,2019.0,4000.00,NaN,NaN
62,7,Charleston,SC,2012-06-18,2012.0,23000.00,NaN,NaN
63,8,Charleston,SC,2017-01-06,2017.0,150000.00,NaN,NaN
64,9,Charleston,SC,2013-02-28,2013.0,50000.00,NaN,NaN
65,10,Charleston,SC,2016-06-03,2016.0,80000.00,NaN,NaN
66,11,Charleston,SC,2015-03-17,2015.0,8000.00,NaN,NaN
67,12,Charleston,SC,2017-06-13,2017.0,10000.00,NaN,NaN
68,13,Charleston,SC,2015-02-18,2015.0,5000.00,NaN,NaN
69,14,Charleston,SC,2019-06-24,2019.0,10000.00,NaN,NaN
70,15,Charleston,SC,2016-06-29,2016.0,3000.00,NaN,NaN
71,16,Charleston,SC,2015-01-29,2015.0,10000.00,NaN,NaN
72,17,Charleston,SC,2014-11-12,2014.0,600000.00,NaN,NaN
73,18,Charleston,SC,2013-10-11,2013.0,6000.00,NaN,NaN
74,19,Charleston,SC,2013-12-05,2013.0,0.00,NaN,NaN
75,20,Charleston,SC,2017-02-16,2017.0,57500.00,NaN,NaN
76,21,Charleston,SC,2018-07-18,2018.0,80000.00,NaN,NaN
77,22,Charleston,SC,2015-12-23,2015.0,0.00,NaN,NaN
78,23,Charleston,SC,2010-07-28,2010.0,5500.00,NaN,NaN
79,24,Charleston,SC,2019-01-24,2019.0,85000.00,NaN,NaN
80,25,Charleston,SC,2011-01-24,2011.0,4000.00,NaN,NaN
81,26,Charleston,SC,2014-12-03,2014.0,1000.00,NaN,NaN
82,27,Charleston,SC,2018-03-08,2018.0,100000.00,NaN,NaN
83,28,Charleston,SC,2014-05-05,2014.0,0.00,NaN,NaN
84,29,Charleston,SC,2017-05-05,2017.0,0.00,NaN,NaN
85,30,Charleston,SC,2015-07-02,2015.0,0.00,NaN,NaN
86,31,Charleston,SC,2018-08-06,2018.0,0.00,NaN,NaN
87,32,Charleston,SC,2011-11-07,2011.0,0.00,NaN,NaN
88,33,Charleston,SC,2010-04-19,2010.0,0.00,NaN,NaN
89,34,Charleston,SC,2010-05-28,2010.0,0.00,NaN,NaN
90,35,Charleston,SC,2011-06-23,2011.0,0.00,NaN,NaN
91,36,Charleston,SC,2011-10-03,2011.0,0.00,NaN,NaN
92,37,Charleston,SC,2013-08-01,2013.0,0.00,NaN,NaN
93,38,Charleston,SC,2012-04-24,2012.0,0.00,NaN,NaN
94,39,Charleston,SC,2011-09-07,2011.0,0.00,NaN,NaN
95,40,Charleston,SC,2012-07-30,2012.0,0.00,NaN,NaN
96,41,Charleston,SC,2014-08-11,2014.0,0.00,NaN,NaN
97,42,Charleston,SC,2018-07-23,2018.0,0.00,NaN,NaN
98,43,Charleston,SC,2018-03-08,2018.0,25000.00,NaN,NaN
99,44,Charleston,SC,2014-06-04,2014.0,5000.00,NaN,NaN
100,45,Charleston,SC,2019-04-15,2019.0,22500.00,NaN,NaN
101,46,Charleston,SC,2011-10-03,2011.0,0.00,NaN,NaN
102,47,Charleston,SC,2013-03-11,2013.0,20000.00,NaN,NaN
103,48,Charleston,SC,2014-03-19,2014.0,0.00,NaN,NaN
104,49,Charleston,SC,2017-07-27,2017.0,0.00,NaN,NaN
105,50,Charleston,SC,2012-09-04,2012.0,0.00,NaN,NaN
106,51,Charleston,SC,2015-10-30,2015.0,0.00,NaN,NaN
107,52,Charleston,SC,2012-07-16,2012.0,0.00,NaN,NaN
108,53,Charleston,SC,2017-03-29,2017.0,40000.00,NaN,NaN
109,54,Charleston,SC,2017-03-29,2017.0,2500.00,NaN,NaN
110,55,Charleston,SC,2017-03-29,2017.0,2500.00,NaN,NaN
111,56,Charleston,SC,2016-12-30,2016.0,250.00,NaN,NaN
112,57,Charleston,SC,2015-12-21,2015.0,0.00,NaN,NaN
113,58,Charleston,SC,2018-05-04,2018.0,0.00,NaN,NaN
114,0,Cincinnati,OH,2015-10-29,2015.0,130000.00,NaN,NaN
115,1,Cincinnati,OH,2014-03-03,2014.0,9000.00,NaN,NaN
116,2,Cincinnati,OH,2015-04-06,2015.0,500.00,NaN,NaN
117,3,Cincinnati,OH,2014-01-24,2014.0,50000.00,NaN,NaN
118,4,Cincinnati,OH,2014-12-17,2014.0,505000.00,NaN,NaN
119,5,Cincinnati,OH,2012-09-27,2012.0,90000.00,NaN,NaN
120,6,Cincinnati,OH,2011-01-01,2011.0,5000.00,NaN,NaN
121,7,Cincinnati,OH,2014-04-08,2014.0,37000.00,NaN,NaN
122,8,Cincinnati,OH,2012-06-12,2012.0,60000.00,NaN,NaN
123,9,Cincinnati,OH,2015-08-20,2015.0,12500.00,NaN,NaN
124,10,Cincinnati,OH,2017-07-13,2017.0,5500.00,NaN,NaN
125,11,Cincinnati,OH,2011-12-06,2011.0,22750.00,NaN,NaN
126,12,Cincinnati,OH,2015-06-18,2015.0,9000.00,NaN,NaN
127,13,Cincinnati,OH,2019-03-14,2019.0,11000.00,NaN,NaN
128,14,Cincinnati,OH,2015-12-09,2015.0,15000.00,NaN,NaN
129,15,Cincinnati,OH,2020-04-15,2020.0,24000.00,NaN,NaN
130,16,Cincinnati,OH,2018-07-24,2018.0,100000.00,NaN,NaN
131,17,Cincinnati,OH,2017-07-13,2017.0,15500.00,NaN,NaN
132,18,Cincinnati,OH,2017-05-08,2017.0,95000.00,NaN,NaN
133,19,Cincinnati,OH,2018-03-06,2018.0,87770.31,NaN,NaN
134,20,Cincinnati,OH,2017-07-13,2017.0,2350.00,NaN,NaN
135,21,Cincinnati,OH,2019-12-31,2019.0,4037.83,NaN,NaN
136,22,Cincinnati,OH,2019-04-30,2019.0,15000.00,NaN,NaN
137,23,Cincinnati,OH,2019-01-11,2019.0,220000.00,NaN,NaN
138,24,Cincinnati,OH,2010-11-05,2010.0,5000.00,NaN,NaN
139,25,Cincinnati,OH,2012-09-19,2012.0,17500.00,NaN,NaN
140,26,Cincinnati,OH,2011-12-19,2011.0,5000.00,NaN,NaN
141,27,Cincinnati,OH,2019-07-17,2019.0,151000.00,NaN,NaN
142,28,Cincinnati,OH,2015-01-14,2015.0,25000.00,NaN,NaN
143,29,Cincinnati,OH,2020-07-06,2020.0,100000.00,NaN,NaN
144,30,Cincinnati,OH,2014-10-01,2014.0,6000.00,NaN,NaN
145,31,Cincinnati,OH,2018-10-22,2018.0,25000.00,NaN,NaN
146,32,Cincinnati,OH,2013-10-25,2013.0,40000.00,NaN,NaN
147,33,Cincinnati,OH,2012-01-03,2012.0,30000.00,NaN,NaN
148,34,Cincinnati,OH,2014-09-17,2014.0,4250.00,NaN,NaN
149,35,Cincinnati,OH,2014-12-15,2014.0,3000.00,NaN,NaN
150,36,Cincinnati,OH,2019-04-08,2019.0,9793.00,NaN,NaN
151,37,Cincinnati,OH,2019-01-07,2019.0,90000.00,NaN,NaN
152,38,Cincinnati,OH,2015-09-17,2015.0,187500.00,NaN,NaN
153,39,Cincinnati,OH,2013-01-15,2013.0,25000.00,NaN,NaN
154,40,Cincinnati,OH,2017-07-13,2017.0,2250.00,NaN,NaN
155,41,Cincinnati,OH,2012-06-06,2012.0,29500.00,NaN,NaN
156,42,Cincinnati,OH,2017-08-07,2017.0,13500.00,NaN,NaN
157,43,Cincinnati,OH,2014-12-04,2014.0,15000.00,NaN,NaN
158,44,Cincinnati,OH,2016-11-07,2016.0,8000.00,NaN,NaN
159,45,Cincinnati,OH,2014-10-01,2014.0,7500.00,NaN,NaN
160,46,Cincinnati,OH,2012-12-12,2012.0,3000.00,NaN,NaN
161,47,Cincinnati,OH,2017-07-13,2017.0,12500.00,NaN,NaN
162,48,Cincinnati,OH,2019-09-27,2019.0,27847.49,NaN,NaN
163,49,Cincinnati,OH,2017-07-13,2017.0,62838.35,NaN,NaN
164,50,Cincinnati,OH,2010-06-24,2010.0,5900.00,NaN,NaN
165,51,Cincinnati,OH,2012-06-27,2012.0,5000.00,NaN,NaN
166,52,Cincinnati,OH,2016-03-15,2016.0,17500.00,NaN,NaN
167,53,Cincinnati,OH,2017-07-13,2017.0,12500.00,NaN,NaN
168,0,Columbia,SC,2017-09-05,2017.0,25000.00,NaN,NaN
169,1,Columbia,SC,2013-07-19,2013.0,50000.00,NaN,NaN
170,2,Columbia,SC,2017-07-31,2017.0,5000.00,NaN,NaN
171,3,Columbia,SC,2013-12-18,2013.0,13500.00,NaN,NaN
172,4,Columbia,SC,2019-03-28,2019.0,2500.00,NaN,NaN
173,5,Columbia,SC,NaN,2018.0,18000.00,NaN,NaN
174,6,Columbia,SC,2015-10-13,2015.0,3000.00,NaN,NaN
175,7,Columbia,SC,2010-11-16,2010.0,10.00,NaN,NaN
176,8,Columbia,SC,2012-10-05,2012.0,15000.00,NaN,NaN
177,9,Columbia,SC,2018-07-30,2018.0,10000.00,NaN,NaN
178,10,Columbia,SC,2015-01-30,2015.0,25000.00,NaN,NaN
179,11,Columbia,SC,2018-12-06,2018.0,8625.00,NaN,NaN
180,12,Columbia,SC,2014-09-22,2014.0,15000.00,NaN,NaN
181,13,Columbia,SC,NaN,NaN,300000.00,NaN,NaN
182,14,Columbia,SC,2016-03-18,2016.0,180000.00,NaN,NaN
183,15,Columbia,SC,2017-07-03,2017.0,15000.00,NaN,NaN
184,16,Columbia,SC,2016-12-05,2016.0,60000.00,NaN,NaN
185,17,Columbia,SC,2015-09-18,2015.0,12800.00,NaN,NaN
186,18,Columbia,SC,NaN,NaN,15000.00,NaN,NaN
187,19,Columbia,SC,2017-03-03,2017.0,22000.00,NaN,NaN
188,20,Columbia,SC,2013-02-15,2013.0,43000.00,NaN,NaN
189,21,Columbia,SC,2014-10-02,2014.0,27500.00,NaN,NaN
190,22,Columbia,SC,2015-01-02,2015.0,13500.00,NaN,NaN
191,23,Columbia,SC,2013-04-17,2013.0,10000.00,NaN,NaN
192,24,Columbia,SC,2016-05-02,2016.0,185000.00,NaN,NaN
193,25,Columbia,SC,2010-09-17,2010.0,4500.00,NaN,NaN
194,26,Columbia,SC,2017-05-17,2017.0,8000.00,NaN,NaN
195,27,Columbia,SC,NaN,NaN,6500.00,NaN,NaN
196,28,Columbia,SC,2016-06-13,2016.0,9000.00,NaN,NaN
197,29,Columbia,SC,2017-01-12,2017.0,250000.00,NaN,NaN
198,0,Little Rock,AR,NaN,NaN,5000.00,NaN,2008-12-20
199,1,Little Rock,AR,NaN,NaN,10000.00,NaN,2008-04-10
200,2,Little Rock,AR,NaN,NaN,2700.00,NaN,2010-08-12
201,3,Little Rock,AR,NaN,NaN,6750.00,NaN,2012-07-01
202,4,Little Rock,AR,NaN,NaN,15000.00,NaN,2011-10-29
203,5,Little Rock,AR,NaN,NaN,90000.00,NaN,2009-11-03
204,6,Little Rock,AR,NaN,NaN,810000.00,NaN,2010-12-09
205,7,Little Rock,AR,NaN,NaN,4500.00,NaN,2015-06-01
206,0,Orlando,FL,2012-11-14,2012.0,6000.00,NaN,2010-03-29
207,1,Orlando,FL,2015-03-20,2015.0,4000.00,NaN,2010-06-15
208,2,Orlando,FL,2014-03-03,2014.0,90000.00,NaN,2010-08-10
209,3,Orlando,FL,NaN,NaN,880000.00,NaN,2010-09-18
210,4,Orlando,FL,2013-03-04,2013.0,3000.00,NaN,2010-11-11
211,5,Orlando,FL,NaN,NaN,750000.00,NaN,2010-11-21
212,6,Orlando,FL,NaN,NaN,140000.00,NaN,2011-02-25
213,7,Orlando,FL,NaN,NaN,24999.99,NaN,2011-04-21
214,8,Orlando,FL,NaN,NaN,17500.00,NaN,2011-12-03
215,9,Orlando,FL,NaN,NaN,15000.00,NaN,2011-12-30
216,10,Orlando,FL,NaN,NaN,5000.00,NaN,2011-12-30
217,11,Orlando,FL,NaN,NaN,100000.00,NaN,2012-08-01
218,12,Orlando,FL,NaN,NaN,10000.00,NaN,2012-09-12
219,13,Orlando,FL,NaN,NaN,5000.00,NaN,2012-12-12
220,14,Orlando,FL,NaN,NaN,30000.00,NaN,2013-01-01
221,15,Orlando,FL,NaN,NaN,125000.00,NaN,2013-01-15
222,16,Orlando,FL,NaN,NaN,760000.00,NaN,2013-01-16
223,17,Orlando,FL,NaN,NaN,15000.00,NaN,2013-01-22
224,18,Orlando,FL,2015-05-21,2015.0,75000.00,NaN,2013-04-30
225,19,Orlando,FL,2016-06-08,2016.0,40000.00,NaN,2013-03-24
226,20,Orlando,FL,2014-07-07,2014.0,5000.00,NaN,2013-03-23
227,21,Orlando,FL,2016-05-19,2016.0,5000.00,NaN,2013-02-27
228,22,Orlando,FL,2017-01-23,2017.0,3000.00,NaN,2013-08-02
229,23,Orlando,FL,2016-04-12,2016.0,5000.00,NaN,2013-09-26
230,24,Orlando,FL,2017-06-16,2017.0,50000.00,NaN,2013-10-04
231,25,Orlando,FL,2015-05-29,2015.0,40878.60,NaN,2013-12-07
232,26,Orlando,FL,2018-08-20,2018.0,95000.00,NaN,2014-07-05
233,27,Orlando,FL,2016-10-11,2016.0,5000.00,NaN,2014-08-07
234,28,Orlando,FL,2017-06-16,2017.0,24999.99,NaN,2014-08-08
235,29,Orlando,FL,2019-02-15,2019.0,2500.00,NaN,2014-08-10
236,30,Orlando,FL,2019-02-15,2019.0,2500.00,NaN,2014-08-10
237,31,Orlando,FL,2017-09-26,2017.0,80000.00,NaN,2014-08-12
238,32,Orlando,FL,2016-07-08,2016.0,7500.00,NaN,2014-11-16
239,33,Orlando,FL,2020-06-25,2020.0,95000.00,NaN,2015-06-04
240,34,Orlando,FL,2016-10-20,2016.0,5000.00,NaN,2014-07-05
241,35,Orlando,FL,2020-06-10,2020.0,50000.00,NaN,2016-01-06
242,36,Orlando,FL,2019-01-07,2019.0,15000.00,NaN,2017-03-04
243,37,Orlando,FL,2019-08-23,2019.0,25000.00,NaN,2018-01-04

In [12]:
chimiala = pd.read_csv('chimiala.csv')

In [13]:
chimiala

      calendar_year         city state closed_date  amount_awarded
0              2019      Chicago    IL  2019-01-29       160000.00
1              2018      Chicago    IL  2018-10-02       100000.00
2              2019      Chicago    IL  2019-05-30        70000.00
3              2010      Chicago    IL  2010-09-24        60000.00
4              2010      Chicago    IL  2010-03-18        99000.00
5              2010      Chicago    IL  2010-03-31        22500.00
6              2010      Chicago    IL  2010-01-28        16000.00
7              2010      Chicago    IL  2010-11-19      2133000.00
8              2011      Chicago    IL  2011-12-27        23000.00
9              2011      Chicago    IL  2011-10-14      1376446.02
10             2010      Chicago    IL  2010-12-03        56750.00
11             2010      Chicago    IL  2010-05-18        10000.00
12             2013      Chicago    IL  2013-08-15      8506616.42
13             2013      Chicago    IL  2013-02-26        51000.00
14             2012      Chicago    IL  2012-03-15       100000.00
15             2010      Chicago    IL  2010-01-06        18000.00
16             2010      Chicago    IL  2010-02-19         2616.80
17             2013      Chicago    IL  2013-01-14       325000.00
18             2011      Chicago    IL  2011-03-31        60000.00
19             2011      Chicago    IL  2011-02-04        10000.00
20             2011      Chicago    IL  2011-04-29         5000.00
21             2012      Chicago    IL  2012-02-09       750000.00
22             2010      Chicago    IL  2010-10-27         1000.00
23             2012      Chicago    IL  2012-11-08       100000.00
24             2010      Chicago    IL  2010-04-26         5500.00
25             2012      Chicago    IL  2012-11-02         3564.33
26             2012      Chicago    IL  2012-10-16        30000.00
27             2013      Chicago    IL  2013-11-12       100000.00
28             2010      Chicago    IL  2010-03-11        15000.00
29             2013      Chicago    IL  2013-07-25        46250.00
30             2014      Chicago    IL  2014-10-06       100000.00
31             2011      Chicago    IL  2011-02-10        75000.00
32             2011      Chicago    IL  2011-02-16        12000.00
33             2015      Chicago    IL  2015-05-21      1500000.00
34             2010      Chicago    IL  2010-05-11         2750.00
35             2013      Chicago    IL  2013-03-25        43000.00
36             2011      Chicago    IL  2011-05-24        10000.00
37             2013      Chicago    IL  2013-11-12        30000.00
38             2015      Chicago    IL  2015-09-22       500000.00
39             2012      Chicago    IL  2012-02-24          500.00
40             2013      Chicago    IL  2013-09-30        60000.00
41             2013      Chicago    IL  2013-04-22        15000.00
42             2013      Chicago    IL  2013-09-23        30000.00
43             2013      Chicago    IL  2013-11-06        75000.00
44             2012      Chicago    IL  2012-12-17         2397.00
45             2014      Chicago    IL  2014-07-08         1000.00
46             2013      Chicago    IL  2013-09-24         2718.73
47             2013      Chicago    IL  2013-09-24      1000000.00
48             2013      Chicago    IL  2013-05-17        50000.00
49             2014      Chicago    IL  2014-04-14      1616500.00
50             2011      Chicago    IL  2011-05-09       115000.00
51             2012      Chicago    IL  2012-11-07      2400000.00
52             2012      Chicago    IL  2012-06-12       950000.00
53             2012      Chicago    IL  2012-03-15         1150.00
54             2012      Chicago    IL  2012-05-22      1135840.00
55             2012      Chicago    IL  2012-02-14         3000.00
56             2010      Chicago    IL  2010-05-14     16500000.00
57             2013      Chicago    IL  2013-11-04      3500000.00
58             2012      Chicago    IL  2012-07-25       425000.00
59             2012      Chicago    IL  2012-07-25       575000.00
60             2010      Chicago    IL  2010-04-16        99000.00
61             2010      Chicago    IL  2010-03-11            1.00
62             2013      Chicago    IL  2013-09-30       315000.00
63             2010      Chicago    IL  2010-06-16      1043750.00
64             2010      Chicago    IL  2010-06-16       397143.67
65             2012      Chicago    IL  2012-03-22       700000.00
66             2012      Chicago    IL  2012-02-09      1328269.68
67             2012      Chicago    IL  2012-06-05        65000.00
68             2013      Chicago    IL  2013-02-07     15000000.00
69             2011      Chicago    IL  2011-12-16      2025000.00
70             2012      Chicago    IL  2012-09-27        19998.00
71             2014      Chicago    IL  2014-02-20       125000.00
72             2015      Chicago    IL  2015-10-19      4100000.00
73             2012      Chicago    IL  2012-02-27        70000.00
74             2014      Chicago    IL  2014-07-18      1100000.00
75             2014      Chicago    IL  2014-05-23       796500.00
76             2010      Chicago    IL  2010-10-15       100000.00
77             2016      Chicago    IL  2016-07-26       550000.00
78             2011      Chicago    IL  2011-03-29       880000.00
79             2012      Chicago    IL  2012-10-05       200000.00
80             2012      Chicago    IL  2012-10-05        26000.00
81             2011      Chicago    IL  2011-01-13      1553000.00
82             2011      Chicago    IL  2011-09-06      1250000.00
83             2011      Chicago    IL  2011-05-04       100000.00
84             2016      Chicago    IL  2016-01-29      2200000.00
85             2014      Chicago    IL  2014-01-21       485000.00
86             2013      Chicago    IL  2013-08-08       430000.00
87             2012      Chicago    IL  2012-08-10      1465000.00
88             2012      Chicago    IL  2012-11-13       850000.00
89             2013      Chicago    IL  2013-07-23         2500.00
90             2014      Chicago    IL  2014-04-29         3000.00
91             2010      Chicago    IL  2010-12-16       400000.00
92             2012      Chicago    IL  2012-01-31      3600000.00
93             2013      Chicago    IL  2013-12-03        21000.00
94             2012      Chicago    IL  2012-08-22       100000.00
95             2011      Chicago    IL  2011-08-30        60000.00
96             2012      Chicago    IL  2012-07-20        85000.00
97             2016      Chicago    IL  2016-11-17       100000.00
98             2012      Chicago    IL  2012-02-21        45000.00
99             2011      Chicago    IL  2011-11-08       547500.00
100            2011      Chicago    IL  2011-08-26         9000.00
101            2015      Chicago    IL  2015-11-12       200000.00
102            2014      Chicago    IL  2014-03-12       100000.00
103            2012      Chicago    IL  2012-12-04       500000.00
104            2013      Chicago    IL  2013-04-29       244980.00
105            2012      Chicago    IL  2012-07-31         5000.00
106            2011      Chicago    IL  2011-11-28         2000.00
107            2011      Chicago    IL  2011-12-06        10000.00
108            2011      Chicago    IL  2011-11-30       560000.00
109            2010      Chicago    IL  2010-04-23         6000.00
110            2016      Chicago    IL  2016-04-21        46000.00
111            2013      Chicago    IL  2013-05-08       100000.00
112            2012      Chicago    IL  2012-10-18        21000.00
113            2010      Chicago    IL  2010-07-20        55000.00
114            2010      Chicago    IL  2010-11-24        54000.00
115            2012      Chicago    IL  2012-07-13         5000.00
116            2010      Chicago    IL  2010-12-01         9000.00
117            2012      Chicago    IL  2012-01-31         9000.00
118            2011      Chicago    IL  2011-11-28       290000.00
119            2012      Chicago    IL  2012-01-19       100000.00
120            2010      Chicago    IL  2010-04-05         3000.00
121            2012      Chicago    IL  2012-08-27        60000.00
122            2014      Chicago    IL  2014-11-26       473000.00
123            2013      Chicago    IL  2013-01-05       225000.00
124            2012      Chicago    IL  2012-02-13       200000.00
125            2010      Chicago    IL  2010-01-22        45000.00
126            2014      Chicago    IL  2014-07-08         5000.00
127            2011      Chicago    IL  2011-05-26       100000.00
128            2011      Chicago    IL  2011-06-16       167200.00
129            2010      Chicago    IL  2010-02-02        15000.00
130            2011      Chicago    IL  2011-08-15         9500.00
131            2015      Chicago    IL  2015-03-16        65000.00
132            2012      Chicago    IL  2012-10-09        99000.00
133            2012      Chicago    IL  2012-06-06        72500.00
134            2010      Chicago    IL  2010-12-20        99000.00
135            2010      Chicago    IL  2010-04-14        10000.00
136            2013      Chicago    IL  2013-03-25      1800000.00
137            2012      Chicago    IL  2012-04-06        20000.00
138            2011      Chicago    IL  2011-07-29       246618.00
139            2010      Chicago    IL  2010-09-30       100000.00
140            2014      Chicago    IL  2014-04-09       100000.00
141            2010      Chicago    IL  2010-04-15        35000.00
142            2013      Chicago    IL  2013-12-16        55000.00
143            2011      Chicago    IL  2011-04-04       392000.00
144            2010      Chicago    IL  2010-10-28         3125.00
145            2010      Chicago    IL  2010-02-10        22642.40
146            2011      Chicago    IL  2011-12-23       122896.08
147            2011      Chicago    IL  2011-02-18       215000.00
148            2010      Chicago    IL  2010-06-11        30000.00
149            2017      Chicago    IL  2017-09-12       395000.00
150            2010      Chicago    IL  2010-10-28         3125.00
151            2012      Chicago    IL  2012-03-08        27500.00
152            2011      Chicago    IL  2011-07-27        32500.00
153            2011      Chicago    IL  2011-09-09        10000.00
154            2011      Chicago    IL  2011-04-25        30000.00
155            2011      Chicago    IL  2011-12-16      1000000.00
156            2011      Chicago    IL  2011-10-21         5000.00
157            2010      Chicago    IL  2010-04-13        35021.00
158            2011      Chicago    IL  2011-05-06         5000.00
159            2010      Chicago    IL  2010-03-31       700000.00
160            2010      Chicago    IL  2010-07-19         1000.00
161            2013      Chicago    IL  2013-05-23        15000.00
162            2013      Chicago    IL  2013-01-03        50000.00
163            2015      Chicago    IL  2015-05-01       340000.00
164            2015      Chicago    IL  2015-01-20        95000.00
165            2013      Chicago    IL  2013-04-25        95000.00
166            2011      Chicago    IL  2011-11-07      6500000.00
167            2014      Chicago    IL  2014-02-06      4500000.00
168            2010      Chicago    IL  2010-10-21        50000.00
169            2010      Chicago    IL  2010-11-03        75000.00
170            2012      Chicago    IL  2012-06-29         7500.00
171            2010      Chicago    IL  2010-04-14        59999.00
172            2010      Chicago    IL  2010-09-09        50000.00
173            2011      Chicago    IL  2011-01-21       185000.00
174            2010      Chicago    IL  2010-09-02         5000.00
175            2016      Chicago    IL  2016-02-23         2477.81
176            2017      Chicago    IL  2017-03-28       336833.00
177            2016      Chicago    IL  2016-05-20        40000.00
178            2016      Chicago    IL  2016-06-17         2019.48
179            2012      Chicago    IL  2012-03-14        20000.00
180            2010      Chicago    IL  2010-11-01        70000.00
181            2010      Chicago    IL  2010-10-19         5400.00
182            2012      Chicago    IL  2012-06-27        85000.00
183            2013      Chicago    IL  2013-05-31         1000.00
184            2010      Chicago    IL  2010-03-17         3000.00
185            2010      Chicago    IL  2010-01-27         8500.00
186            2010      Chicago    IL  2010-01-26         8500.00
187            2011      Chicago    IL  2011-01-14        12800.00
188            2012      Chicago    IL  2012-04-19        99999.00
189            2012      Chicago    IL  2012-08-20       250000.00
190            2012      Chicago    IL  2012-04-10       250000.00
191            2010      Chicago    IL  2010-07-23        80000.00
192            2010      Chicago    IL  2010-04-01        16500.00
193            2010      Chicago    IL  2010-12-29        18000.00
194            2012      Chicago    IL  2012-07-18         6000.00
195            2011      Chicago    IL  2011-02-01         2500.00
196            2010      Chicago    IL  2010-01-11        87000.00
197            2010      Chicago    IL  2010-02-02        25000.00
198            2012      Chicago    IL  2012-05-22       150000.00
199            2014      Chicago    IL  2014-03-31         6000.00
200            2011      Chicago    IL  2011-10-19         1500.00
201            2010      Chicago    IL  2010-07-07        10000.00
202            2010      Chicago    IL  2010-06-03        55000.00
203            2011      Chicago    IL  2011-06-15        60000.00
204            2010      Chicago    IL  2010-12-02       150000.00
205            2011      Chicago    IL  2011-08-10       125680.64
206            2012      Chicago    IL  2012-01-17         5000.00
207            2012      Chicago    IL  2012-07-12       375000.00
208            2012      Chicago    IL  2012-04-25         2500.00
209            2012      Chicago    IL  2012-09-20        80000.00
210            2017      Chicago    IL  2017-04-26       370000.00
211            2011      Chicago    IL  2011-09-07        65000.00
212            2010      Chicago    IL  2010-01-06        12000.00
213            2011      Chicago    IL  2011-03-24         4100.00
214            2012      Chicago    IL  2012-09-13        30000.00
215            2013      Chicago    IL  2013-01-23        40000.00
216            2010      Chicago    IL  2010-06-30       143152.56
217            2010      Chicago    IL  2010-10-26         7500.00
218            2011      Chicago    IL  2011-01-03        50000.00
219            2010      Chicago    IL  2010-04-15         6500.00
220            2011      Chicago    IL  2011-11-21       128170.79
221            2013      Chicago    IL  2013-10-18         7500.00
222            2011      Chicago    IL  2011-09-23         3000.00
223            2011      Chicago    IL  2011-10-25        50000.00
224            2010      Chicago    IL  2010-10-20        15000.00
225            2014      Chicago    IL  2014-12-16      7625000.00
226            2011      Chicago    IL  2011-04-29        10000.00
227            2012      Chicago    IL  2012-03-30        12000.00
228            2013      Chicago    IL  2013-07-22        50000.00
229            2011      Chicago    IL  2011-09-13         1000.00
230            2013      Chicago    IL  2013-03-28       120000.00
231            2012      Chicago    IL  2012-04-10        13500.00
232            2011      Chicago    IL  2011-04-26        99000.00
233            2010      Chicago    IL  2010-04-12         6000.00
234            2010      Chicago    IL  2010-04-22        99000.00
235            2010      Chicago    IL  2010-06-01       450000.00
236            2011      Chicago    IL  2011-03-02        47500.00
237            2010      Chicago    IL  2010-11-02         1000.00
238            2011      Chicago    IL  2011-11-30        15000.00
239            2011      Chicago    IL  2011-07-15        10000.00
240            2012      Chicago    IL  2012-08-17         3000.00
241            2012      Chicago    IL  2012-01-23        80000.00
242            2011      Chicago    IL  2011-02-01        37500.00
243            2012      Chicago    IL  2012-08-30        45000.00
244            2012      Chicago    IL  2012-03-14         8000.00
245            2014      Chicago    IL  2014-05-05         3500.00
246            2012      Chicago    IL  2012-09-17        42500.00
247            2012      Chicago    IL  2012-10-12        85000.00
248            2011      Chicago    IL  2011-07-25        12960.86
249            2010      Chicago    IL  2010-03-22        25000.00
250            2013      Chicago    IL  2013-02-13         5000.00
251            2014      Chicago    IL  2014-01-21       100000.00
252            2011      Chicago    IL  2011-01-19        44000.00
253            2011      Chicago    IL  2011-01-27        75000.00
254            2011      Chicago    IL  2011-01-18        75000.00
255            2011      Chicago    IL  2011-01-14        30000.00
256            2011      Chicago    IL  2011-02-11        10000.00
257            2010      Chicago    IL  2010-11-22        98000.00
258            2010      Chicago    IL  2010-09-08        80000.00
259            2010      Chicago    IL  2010-09-08        25000.00
260            2011      Chicago    IL  2011-01-03        96000.00
261            2011      Chicago    IL  2011-09-26       155000.00
262            2011      Chicago    IL  2011-05-12        14310.53
263            2011      Chicago    IL  2011-07-21        22000.00
264            2010      Chicago    IL  2010-06-15        99000.00
265            2012      Chicago    IL  2012-09-20        87250.00
266            2015      Chicago    IL  2015-02-18        50000.00
267            2011      Chicago    IL  2011-12-20        17000.00
268            2011      Chicago    IL  2011-06-27       152000.00
269            2011      Chicago    IL  2011-11-17         5000.00
270            2011      Chicago    IL  2011-03-17        95000.00
271            2013      Chicago    IL  2013-09-25         5000.00
272            2012      Chicago    IL  2012-03-22       125000.00
273            2011      Chicago    IL  2011-07-20         3023.35
274            2013      Chicago    IL  2013-05-15        69500.00
275            2014      Chicago    IL  2014-02-14       161000.00
276            2012      Chicago    IL  2012-06-05       165000.00
277            2012      Chicago    IL  2012-09-12        10000.00
278            2012      Chicago    IL  2012-05-09        30000.00
279            2013      Chicago    IL  2013-06-06        23000.00
280            2013      Chicago    IL  2013-02-13     10250000.00
281            2013      Chicago    IL  2013-02-08         7500.00
282            2013      Chicago    IL  2013-05-03        20000.00
283            2012      Chicago    IL  2012-12-01        14999.89
284            2013      Chicago    IL  2013-01-10       390000.00
285            2012      Chicago    IL  2012-09-17        40000.00
286            2011      Chicago    IL  2011-03-24       112500.00
287            2010      Chicago    IL  2010-02-02        38000.00
288            2010      Chicago    IL  2010-08-11        16000.00
289            2014      Chicago    IL  2014-05-29       100000.00
290            2014      Chicago    IL  2014-05-29       550000.00
291            2011      Chicago    IL  2011-02-03        17500.00
292            2012      Chicago    IL  2012-09-27        29000.00
293            2011      Chicago    IL  2011-10-27        95000.00
294            2012      Chicago    IL  2012-11-01        85000.00
295            2012      Chicago    IL  2012-08-21        80000.00
296            2011      Chicago    IL  2011-08-04        38000.00

In [14]:
jaimie = pd.concat([chimiala, all_cities])

In [15]:
total = jaimie.groupby('city')[['amount_awarded']].sum()

In [16]:
total.round()

             amount_awarded
city
Boston           11905482.0
Cambridge          114000.0
Charleston        1520250.0
Chicago         467586464.0
Cincinnati        2472787.0
Columbia          1352435.0
Little Rock        943950.0
Los Angeles     329925622.0
Miami             7284684.0
Orlando           3611879.0

In [17]:
jaimie.to_csv('jaimie.csv', index=False)

In [18]:
jaimie_view = pd.read_csv('jaimie.csv')

In [19]:
jaimie_view

      calendar_year         city state closed_date  amount_awarded  \
0            2019.0      Chicago    IL  2019-01-29       160000.00
1            2018.0      Chicago    IL  2018-10-02       100000.00
2            2019.0      Chicago    IL  2019-05-30        70000.00
3            2010.0      Chicago    IL  2010-09-24        60000.00
4            2010.0      Chicago    IL  2010-03-18        99000.00
5            2010.0      Chicago    IL  2010-03-31        22500.00
6            2010.0      Chicago    IL  2010-01-28        16000.00
7            2010.0      Chicago    IL  2010-11-19      2133000.00
8            2011.0      Chicago    IL  2011-12-27        23000.00
9            2011.0      Chicago    IL  2011-10-14      1376446.02
10           2010.0      Chicago    IL  2010-12-03        56750.00
11           2010.0      Chicago    IL  2010-05-18        10000.00
12           2013.0      Chicago    IL  2013-08-15      8506616.42
13           2013.0      Chicago    IL  2013-02-26        51000.00
14           2012.0      Chicago    IL  2012-03-15       100000.00
15           2010.0      Chicago    IL  2010-01-06        18000.00
16           2010.0      Chicago    IL  2010-02-19         2616.80
17           2013.0      Chicago    IL  2013-01-14       325000.00
18           2011.0      Chicago    IL  2011-03-31        60000.00
19           2011.0      Chicago    IL  2011-02-04        10000.00
20           2011.0      Chicago    IL  2011-04-29         5000.00
21           2012.0      Chicago    IL  2012-02-09       750000.00
22           2010.0      Chicago    IL  2010-10-27         1000.00
23           2012.0      Chicago    IL  2012-11-08       100000.00
24           2010.0      Chicago    IL  2010-04-26         5500.00
25           2012.0      Chicago    IL  2012-11-02         3564.33
26           2012.0      Chicago    IL  2012-10-16        30000.00
27           2013.0      Chicago    IL  2013-11-12       100000.00
28           2010.0      Chicago    IL  2010-03-11        15000.00
29           2013.0      Chicago    IL  2013-07-25        46250.00
30           2014.0      Chicago    IL  2014-10-06       100000.00
31           2011.0      Chicago    IL  2011-02-10        75000.00
32           2011.0      Chicago    IL  2011-02-16        12000.00
33           2015.0      Chicago    IL  2015-05-21      1500000.00
34           2010.0      Chicago    IL  2010-05-11         2750.00
35           2013.0      Chicago    IL  2013-03-25        43000.00
36           2011.0      Chicago    IL  2011-05-24        10000.00
37           2013.0      Chicago    IL  2013-11-12        30000.00
38           2015.0      Chicago    IL  2015-09-22       500000.00
39           2012.0      Chicago    IL  2012-02-24          500.00
40           2013.0      Chicago    IL  2013-09-30        60000.00
41           2013.0      Chicago    IL  2013-04-22        15000.00
42           2013.0      Chicago    IL  2013-09-23        30000.00
43           2013.0      Chicago    IL  2013-11-06        75000.00
44           2012.0      Chicago    IL  2012-12-17         2397.00
45           2014.0      Chicago    IL  2014-07-08         1000.00
46           2013.0      Chicago    IL  2013-09-24         2718.73
47           2013.0      Chicago    IL  2013-09-24      1000000.00
48           2013.0      Chicago    IL  2013-05-17        50000.00
49           2014.0      Chicago    IL  2014-04-14      1616500.00
50           2011.0      Chicago    IL  2011-05-09       115000.00
51           2012.0      Chicago    IL  2012-11-07      2400000.00
52           2012.0      Chicago    IL  2012-06-12       950000.00
53           2012.0      Chicago    IL  2012-03-15         1150.00
54           2012.0      Chicago    IL  2012-05-22      1135840.00
55           2012.0      Chicago    IL  2012-02-14         3000.00
56           2010.0      Chicago    IL  2010-05-14     16500000.00
57           2013.0      Chicago    IL  2013-11-04      3500000.00
58           2012.0      Chicago    IL  2012-07-25       425000.00
59           2012.0      Chicago    IL  2012-07-25       575000.00
60           2010.0      Chicago    IL  2010-04-16        99000.00
61           2010.0      Chicago    IL  2010-03-11            1.00
62           2013.0      Chicago    IL  2013-09-30       315000.00
63           2010.0      Chicago    IL  2010-06-16      1043750.00
64           2010.0      Chicago    IL  2010-06-16       397143.67
65           2012.0      Chicago    IL  2012-03-22       700000.00
66           2012.0      Chicago    IL  2012-02-09      1328269.68
67           2012.0      Chicago    IL  2012-06-05        65000.00
68           2013.0      Chicago    IL  2013-02-07     15000000.00
69           2011.0      Chicago    IL  2011-12-16      2025000.00
70           2012.0      Chicago    IL  2012-09-27        19998.00
71           2014.0      Chicago    IL  2014-02-20       125000.00
72           2015.0      Chicago    IL  2015-10-19      4100000.00
73           2012.0      Chicago    IL  2012-02-27        70000.00
74           2014.0      Chicago    IL  2014-07-18      1100000.00
75           2014.0      Chicago    IL  2014-05-23       796500.00
76           2010.0      Chicago    IL  2010-10-15       100000.00
77           2016.0      Chicago    IL  2016-07-26       550000.00
78           2011.0      Chicago    IL  2011-03-29       880000.00
79           2012.0      Chicago    IL  2012-10-05       200000.00
80           2012.0      Chicago    IL  2012-10-05        26000.00
81           2011.0      Chicago    IL  2011-01-13      1553000.00
82           2011.0      Chicago    IL  2011-09-06      1250000.00
83           2011.0      Chicago    IL  2011-05-04       100000.00
84           2016.0      Chicago    IL  2016-01-29      2200000.00
85           2014.0      Chicago    IL  2014-01-21       485000.00
86           2013.0      Chicago    IL  2013-08-08       430000.00
87           2012.0      Chicago    IL  2012-08-10      1465000.00
88           2012.0      Chicago    IL  2012-11-13       850000.00
89           2013.0      Chicago    IL  2013-07-23         2500.00
90           2014.0      Chicago    IL  2014-04-29         3000.00
91           2010.0      Chicago    IL  2010-12-16       400000.00
92           2012.0      Chicago    IL  2012-01-31      3600000.00
93           2013.0      Chicago    IL  2013-12-03        21000.00
94           2012.0      Chicago    IL  2012-08-22       100000.00
95           2011.0      Chicago    IL  2011-08-30        60000.00
96           2012.0      Chicago    IL  2012-07-20        85000.00
97           2016.0      Chicago    IL  2016-11-17       100000.00
98           2012.0      Chicago    IL  2012-02-21        45000.00
99           2011.0      Chicago    IL  2011-11-08       547500.00
100          2011.0      Chicago    IL  2011-08-26         9000.00
101          2015.0      Chicago    IL  2015-11-12       200000.00
102          2014.0      Chicago    IL  2014-03-12       100000.00
103          2012.0      Chicago    IL  2012-12-04       500000.00
104          2013.0      Chicago    IL  2013-04-29       244980.00
105          2012.0      Chicago    IL  2012-07-31         5000.00
106          2011.0      Chicago    IL  2011-11-28         2000.00
107          2011.0      Chicago    IL  2011-12-06        10000.00
108          2011.0      Chicago    IL  2011-11-30       560000.00
109          2010.0      Chicago    IL  2010-04-23         6000.00
110          2016.0      Chicago    IL  2016-04-21        46000.00
111          2013.0      Chicago    IL  2013-05-08       100000.00
112          2012.0      Chicago    IL  2012-10-18        21000.00
113          2010.0      Chicago    IL  2010-07-20        55000.00
114          2010.0      Chicago    IL  2010-11-24        54000.00
115          2012.0      Chicago    IL  2012-07-13         5000.00
116          2010.0      Chicago    IL  2010-12-01         9000.00
117          2012.0      Chicago    IL  2012-01-31         9000.00
118          2011.0      Chicago    IL  2011-11-28       290000.00
119          2012.0      Chicago    IL  2012-01-19       100000.00
120          2010.0      Chicago    IL  2010-04-05         3000.00
121          2012.0      Chicago    IL  2012-08-27        60000.00
122          2014.0      Chicago    IL  2014-11-26       473000.00
123          2013.0      Chicago    IL  2013-01-05       225000.00
124          2012.0      Chicago    IL  2012-02-13       200000.00
125          2010.0      Chicago    IL  2010-01-22        45000.00
126          2014.0      Chicago    IL  2014-07-08         5000.00
127          2011.0      Chicago    IL  2011-05-26       100000.00
128          2011.0      Chicago    IL  2011-06-16       167200.00
129          2010.0      Chicago    IL  2010-02-02        15000.00
130          2011.0      Chicago    IL  2011-08-15         9500.00
131          2015.0      Chicago    IL  2015-03-16        65000.00
132          2012.0      Chicago    IL  2012-10-09        99000.00
133          2012.0      Chicago    IL  2012-06-06        72500.00
134          2010.0      Chicago    IL  2010-12-20        99000.00
135          2010.0      Chicago    IL  2010-04-14        10000.00
136          2013.0      Chicago    IL  2013-03-25      1800000.00
137          2012.0      Chicago    IL  2012-04-06        20000.00
138          2011.0      Chicago    IL  2011-07-29       246618.00
139          2010.0      Chicago    IL  2010-09-30       100000.00
140          2014.0      Chicago    IL  2014-04-09       100000.00
141          2010.0      Chicago    IL  2010-04-15        35000.00
142          2013.0      Chicago    IL  2013-12-16        55000.00
143          2011.0      Chicago    IL  2011-04-04       392000.00
144          2010.0      Chicago    IL  2010-10-28         3125.00
145          2010.0      Chicago    IL  2010-02-10        22642.40
146          2011.0      Chicago    IL  2011-12-23       122896.08
147          2011.0      Chicago    IL  2011-02-18       215000.00
148          2010.0      Chicago    IL  2010-06-11        30000.00
149          2017.0      Chicago    IL  2017-09-12       395000.00
150          2010.0      Chicago    IL  2010-10-28         3125.00
151          2012.0      Chicago    IL  2012-03-08        27500.00
152          2011.0      Chicago    IL  2011-07-27        32500.00
153          2011.0      Chicago    IL  2011-09-09        10000.00
154          2011.0      Chicago    IL  2011-04-25        30000.00
155          2011.0      Chicago    IL  2011-12-16      1000000.00
156          2011.0      Chicago    IL  2011-10-21         5000.00
157          2010.0      Chicago    IL  2010-04-13        35021.00
158          2011.0      Chicago    IL  2011-05-06         5000.00
159          2010.0      Chicago    IL  2010-03-31       700000.00
160          2010.0      Chicago    IL  2010-07-19         1000.00
161          2013.0      Chicago    IL  2013-05-23        15000.00
162          2013.0      Chicago    IL  2013-01-03        50000.00
163          2015.0      Chicago    IL  2015-05-01       340000.00
164          2015.0      Chicago    IL  2015-01-20        95000.00
165          2013.0      Chicago    IL  2013-04-25        95000.00
166          2011.0      Chicago    IL  2011-11-07      6500000.00
167          2014.0      Chicago    IL  2014-02-06      4500000.00
168          2010.0      Chicago    IL  2010-10-21        50000.00
169          2010.0      Chicago    IL  2010-11-03        75000.00
170          2012.0      Chicago    IL  2012-06-29         7500.00
171          2010.0      Chicago    IL  2010-04-14        59999.00
172          2010.0      Chicago    IL  2010-09-09        50000.00
173          2011.0      Chicago    IL  2011-01-21       185000.00
174          2010.0      Chicago    IL  2010-09-02         5000.00
175          2016.0      Chicago    IL  2016-02-23         2477.81
176          2017.0      Chicago    IL  2017-03-28       336833.00
177          2016.0      Chicago    IL  2016-05-20        40000.00
178          2016.0      Chicago    IL  2016-06-17         2019.48
179          2012.0      Chicago    IL  2012-03-14        20000.00
180          2010.0      Chicago    IL  2010-11-01        70000.00
181          2010.0      Chicago    IL  2010-10-19         5400.00
182          2012.0      Chicago    IL  2012-06-27        85000.00
183          2013.0      Chicago    IL  2013-05-31         1000.00
184          2010.0      Chicago    IL  2010-03-17         3000.00
185          2010.0      Chicago    IL  2010-01-27         8500.00
186          2010.0      Chicago    IL  2010-01-26         8500.00
187          2011.0      Chicago    IL  2011-01-14        12800.00
188          2012.0      Chicago    IL  2012-04-19        99999.00
189          2012.0      Chicago    IL  2012-08-20       250000.00
190          2012.0      Chicago    IL  2012-04-10       250000.00
191          2010.0      Chicago    IL  2010-07-23        80000.00
192          2010.0      Chicago    IL  2010-04-01        16500.00
193          2010.0      Chicago    IL  2010-12-29        18000.00
194          2012.0      Chicago    IL  2012-07-18         6000.00
195          2011.0      Chicago    IL  2011-02-01         2500.00
196          2010.0      Chicago    IL  2010-01-11        87000.00
197          2010.0      Chicago    IL  2010-02-02        25000.00
198          2012.0      Chicago    IL  2012-05-22       150000.00
199          2014.0      Chicago    IL  2014-03-31         6000.00
200          2011.0      Chicago    IL  2011-10-19         1500.00
201          2010.0      Chicago    IL  2010-07-07        10000.00
202          2010.0      Chicago    IL  2010-06-03        55000.00
203          2011.0      Chicago    IL  2011-06-15        60000.00
204          2010.0      Chicago    IL  2010-12-02       150000.00
205          2011.0      Chicago    IL  2011-08-10       125680.64
206          2012.0      Chicago    IL  2012-01-17         5000.00
207          2012.0      Chicago    IL  2012-07-12       375000.00
208          2012.0      Chicago    IL  2012-04-25         2500.00
209          2012.0      Chicago    IL  2012-09-20        80000.00
210          2017.0      Chicago    IL  2017-04-26       370000.00
211          2011.0      Chicago    IL  2011-09-07        65000.00
212          2010.0      Chicago    IL  2010-01-06        12000.00
213          2011.0      Chicago    IL  2011-03-24         4100.00
214          2012.0      Chicago    IL  2012-09-13        30000.00
215          2013.0      Chicago    IL  2013-01-23        40000.00
216          2010.0      Chicago    IL  2010-06-30       143152.56
217          2010.0      Chicago    IL  2010-10-26         7500.00
218          2011.0      Chicago    IL  2011-01-03        50000.00
219          2010.0      Chicago    IL  2010-04-15         6500.00
220          2011.0      Chicago    IL  2011-11-21       128170.79
221          2013.0      Chicago    IL  2013-10-18         7500.00
222          2011.0      Chicago    IL  2011-09-23         3000.00
223          2011.0      Chicago    IL  2011-10-25        50000.00
224          2010.0      Chicago    IL  2010-10-20        15000.00
225          2014.0      Chicago    IL  2014-12-16      7625000.00
226          2011.0      Chicago    IL  2011-04-29        10000.00
227          2012.0      Chicago    IL  2012-03-30        12000.00
228          2013.0      Chicago    IL  2013-07-22        50000.00
229          2011.0      Chicago    IL  2011-09-13         1000.00
230          2013.0      Chicago    IL  2013-03-28       120000.00
231          2012.0      Chicago    IL  2012-04-10        13500.00
232          2011.0      Chicago    IL  2011-04-26        99000.00
233          2010.0      Chicago    IL  2010-04-12         6000.00
234          2010.0      Chicago    IL  2010-04-22        99000.00
235          2010.0      Chicago    IL  2010-06-01       450000.00
236          2011.0      Chicago    IL  2011-03-02        47500.00
237          2010.0      Chicago    IL  2010-11-02         1000.00
238          2011.0      Chicago    IL  2011-11-30        15000.00
239          2011.0      Chicago    IL  2011-07-15        10000.00
240          2012.0      Chicago    IL  2012-08-17         3000.00
241          2012.0      Chicago    IL  2012-01-23        80000.00
242          2011.0      Chicago    IL  2011-02-01        37500.00
243          2012.0      Chicago    IL  2012-08-30        45000.00
244          2012.0      Chicago    IL  2012-03-14         8000.00
245          2014.0      Chicago    IL  2014-05-05         3500.00
246          2012.0      Chicago    IL  2012-09-17        42500.00
247          2012.0      Chicago    IL  2012-10-12        85000.00
248          2011.0      Chicago    IL  2011-07-25        12960.86
249          2010.0      Chicago    IL  2010-03-22        25000.00
250          2013.0      Chicago    IL  2013-02-13         5000.00
251          2014.0      Chicago    IL  2014-01-21       100000.00
252          2011.0      Chicago    IL  2011-01-19        44000.00
253          2011.0      Chicago    IL  2011-01-27        75000.00
254          2011.0      Chicago    IL  2011-01-18        75000.00
255          2011.0      Chicago    IL  2011-01-14        30000.00
256          2011.0      Chicago    IL  2011-02-11        10000.00
257          2010.0      Chicago    IL  2010-11-22        98000.00
258          2010.0      Chicago    IL  2010-09-08        80000.00
259          2010.0      Chicago    IL  2010-09-08        25000.00
260          2011.0      Chicago    IL  2011-01-03        96000.00
261          2011.0      Chicago    IL  2011-09-26       155000.00
262          2011.0      Chicago    IL  2011-05-12        14310.53
263          2011.0      Chicago    IL  2011-07-21        22000.00
264          2010.0      Chicago    IL  2010-06-15        99000.00
265          2012.0      Chicago    IL  2012-09-20        87250.00
266          2015.0      Chicago    IL  2015-02-18        50000.00
267          2011.0      Chicago    IL  2011-12-20        17000.00
268          2011.0      Chicago    IL  2011-06-27       152000.00
269          2011.0      Chicago    IL  2011-11-17         5000.00
270          2011.0      Chicago    IL  2011-03-17        95000.00
271          2013.0      Chicago    IL  2013-09-25         5000.00
272          2012.0      Chicago    IL  2012-03-22       125000.00
273          2011.0      Chicago    IL  2011-07-20         3023.35
274          2013.0      Chicago    IL  2013-05-15        69500.00
275          2014.0      Chicago    IL  2014-02-14       161000.00
276          2012.0      Chicago    IL  2012-06-05       165000.00
277          2012.0      Chicago    IL  2012-09-12        10000.00
278          2012.0      Chicago    IL  2012-05-09        30000.00
279          2013.0      Chicago    IL  2013-06-06        23000.00
280          2013.0      Chicago    IL  2013-02-13     10250000.00
281          2013.0      Chicago    IL  2013-02-08         7500.00
282          2013.0      Chicago    IL  2013-05-03        20000.00
283          2012.0      Chicago    IL  2012-12-01        14999.89
284          2013.0      Chicago    IL  2013-01-10       390000.00
285          2012.0      Chicago    IL  2012-09-17        40000.00
286          2011.0      Chicago    IL  2011-03-24       112500.00
287          2010.0      Chicago    IL  2010-02-02        38000.00
288          2010.0      Chicago    IL  2010-08-11        16000.00
289          2014.0      Chicago    IL  2014-05-29       100000.00
290          2014.0      Chicago    IL  2014-05-29       550000.00
291          2011.0      Chicago    IL  2011-02-03        17500.00
292          2012.0      Chicago    IL  2012-09-27        29000.00
293          2011.0      Chicago    IL  2011-10-27        95000.00
294          2012.0      Chicago    IL  2012-11-01        85000.00
295          2012.0      Chicago    IL  2012-08-21        80000.00
296          2011.0      Chicago    IL  2011-08-04        38000.00