In [1]:
import pandas as pd

In [2]:
miami_full = pd.read_csv('miami_edited.csv')

In [3]:
miami_full

,calendar_year,city,state,incident_date,incident_year,filed_date,filed_year,closed_date,amount_awarded,other_expenses,...,docket_number,claim_number,court,plaintiff_name,plaintiff_attorney,matter_name,location,summary_allegations,status,opened_date
0,2010,Miami,FL,NaN,NaN,2005-10-04,2005.0,2010-10-08,83000.0,NaN,...,05-19016 CA-22,05-2013,NaN,NaN,Henry J. Hunnefeld,"GARCIA, Agustin, et al. vs. CITY OF MIAMI",NaN,False Arrest w/out Battery,Closed,2005-10-15
1,2010,Miami,FL,NaN,NaN,2006-05-08,2006.0,2010-12-21,15000.0,NaN,...,06-21124-CIV-MARRA,06-884,NaN,NaN,Henry J. Hunnefeld,"LIPPMAN, David vs. CITY OF MIAMI, et al.",NaN,First Amendment w/out Demonstration,Closed,2006-05-10
2,2011,Miami,FL,NaN,NaN,2007-08-01,2007.0,2011-08-31,800.0,NaN,...,07-05781 CA 10,07-1533,NaN,NaN,Tarin A. Smithline,"HARRIS, Trevale vs. CITY OF MIAMI,",NaN,Battery (no False Arrest),Closed,2007-08-06
3,2011,Miami,FL,NaN,NaN,2007-08-10,2007.0,2011-05-04,9500.0,NaN,...,07-25244 CA 27,07-1586,NaN,NaN,Henry J. Hunnefeld,"DAVIS, Eugene vs. CITY OF MIAMI and WILLIAM J...",NaN,False Arrest w/ Battery,Closed,2007-08-14
4,2010,Miami,FL,NaN,NaN,2007-10-11,2007.0,2010-08-11,6500.0,NaN,...,07-33323 CA 05,07-2196,NaN,NaN,Christopher A. Green,"SOTTILE, Anna vs. CITY OF MIAMI, Florida and ...",NaN,Torts,Closed,2007-10-18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,2015,Miami,FL,NaN,NaN,2014-05-15,2014.0,2015-03-17,80000.0,NaN,...,14-CV-21663-Altonaga/O'Sullivan,14-1260,NaN,NaN,Christopher A. Green,"SANON, Polini vs. CITY OF MIAMI, a Municipal C...",NaN,False Arrest w/ Excessive Force,Closed,2014-05-19
83,2017,Miami,FL,NaN,NaN,2014-06-05,2014.0,2017-03-15,19750.0,NaN,...,14-14187 CA 34,14-1433,NaN,NaN,Henry J. Hunnefeld,"ZAPATA, Ufredo vs. CITY OF MIAMI POLICE DEPART...",NaN,Torts,Closed,2014-06-09
84,2020,Miami,FL,NaN,NaN,NaN,NaN,2020-04-07,300000.0,NaN,...,19-13023-B,17-1680.002Appeal,NaN,NaN,Eric J. Eves,"SEVERE, Francois as personal representative of...",NaN,Civil Rights,Closed,2019-08-15
85,2018,Miami,FL,NaN,NaN,2017-06-14,2017.0,2018-08-03,50000.0,NaN,...,1:17-cv-22044-MGC,17-1690,NaN,NaN,Douglas A. Harrison,"GELLINEAU, Ryan vs. STANLEY MIKE, individually...",NaN,False Arrest w/ Excessive Force,Closed,2017-06-15
86,2018,Miami,FL,NaN,NaN,NaN,NaN,2018-10-30,17500.0,NaN,...,16-CV-24904-KMW,17-1828,NaN,NaN,Eric J. Eves,"ALLEN, Richard Dean vs. OFFICER JAVIER GONZALE...",NaN,False Arrest w/ Excessive Force,Closed,2017-06-27

In [4]:
miami_yearly = miami_full.groupby('calendar_year')[['amount_awarded']].sum()

In [5]:
miami_yearly

               amount_awarded
calendar_year
2010                124500.00
2011                632431.00
2012                466750.00
2013                285768.00
2014                113385.00
2015                577550.00
2016               1970512.10
2017                381048.00
2018               1892198.00
2019                175641.76
2020                664900.00

In [8]:
los_angeles_full = pd.read_csv('los_angeles_edited.csv')

In [9]:
los_angeles_yearly = los_angeles_full.groupby('calendar_year')[['amount_awarded']].sum()

In [12]:
los_angeles_yearly_round = los_angeles_yearly.round()